#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x', 'float64' )
record_stream = comma.csv.stream( point_t, fields=',x', format='f8,f8' )

for i,r in enumerate( record_stream.iter(), start=1 ):
  r['x'] += i
  record_stream.write( r )
END
)"
}

csv-to-bin 2d | process_records | csv-from-bin d | output
comma_status_ok
echo "status=$?"

