#!/bin/bash

echo "{called dir7_expect_failure/test}" >&2

function clean()
{
    rm -rf "$workdir" >/dev/null 2>&1
}

trap 'clean' EXIT

output_dir="output"
rm -rf "$output_dir" || exit 1
mkdir -p "$output_dir" || exit 1
output_dir=$( cd "$output_dir" ; pwd )

workdir=$( mktemp --directory )
cp -i -p ./real-test "$workdir/test" || exit 1
cp -i -p ./real-expected "$workdir/expected" || exit 1

cd "$workdir" || exit 1
comma-test-run > "$output_dir/log" 2>&1
(( $? == 0 )) && {
    echo "expected comma-test-run to fail; it did not" >&2
    exit 1   # shall fail
}
exit 0
