#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event,shift', 'S3', timestamped_point_t, 'timedelta64[s]' )
record_stream = comma.csv.stream( record_t, format=','.join( record_t.types ) )

r = record_stream.read()
r['event']['time'] += r['shift']
record_stream.write( r )
END
)"
}

csv-to-bin s[3],t,3d,l | process_records | csv-from-bin s[3],t,3d,l | output
comma_status_ok
echo "status=$?"
