#!/bin/bash

home=$1
[[ -n "$home" ]] || { echo "usage: $0 <packaging-dir>" >&2; exit 1; }
home=$( realpath $home )
mkdir -p $home/src
cd $home/src
git clone https://gitlab.com/orthographic/comma.git
build_dir=$home/src/comma/build
mkdir -p $build_dir
cd $build_dir
cmake $home/src/comma \
    -DCMAKE_INSTALL_PREFIX=$home/src/comma/debian/tmp/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_PYTHON_PACKAGES=OFF \
    -DADD_PYTHON_PACKAGES_TO_RPM=OFF \
    -DBUILD_TESTS=OFF \
    -DINSTALL_BASH_COMPLETION=OFF \
    -DINSTALL_TESTS=OFF \
    -Dcomma_INSTALL_LIB_DIR=lib/x86_64-linux-gnu \
    -Dcomma_INSTALL_PACKAGE_DIR=lib/x86_64-linux-gnu/cmake/comma \
    -Dcomma_INSTALL_RUN_POST_INSTALL=OFF \
    -Dcomma_BUILD_XML=OFF \
    -Dcomma_BUILD_ZEROMQ=OFF \
    -Dcomma_build_io_rabbit_cat=OFF
make -j
make install -j

# make vodoo debian directories
mkdir -p $build_dir/debian/tmp/usr/lib
mkdir -p $build_dir/debian/tmp/DEBIAN

# copy installed lib files (because for some reason comma cmake does not install libraries at the right place; todo: fix!)
cp -r $build_dir/lib/x86_64-linux-gnu $build_dir/debian/tmp/usr/lib

# copy debian configuration files to our build directory for packaging
cp -r $home/src/comma/debian/* $build_dir/debian

# generate the control file
dpkg-gencontrol -pcomma

# build the package
dpkg --build $build_dir/debian/tmp $build_dir
