#!/bin/bash

home=$1
[[ -n "$home" ]] || { echo "usage: $0 <dir>" >&2; exit 1; }
cd $home/src
git clone https://gitlab.com/orthographic/comma.git
build_dir=$home/src/comma/build
mkdir -p $build_dir
cd $build_dir
cmake $home/src/comma \
    -DCMAKE_INSTALL_PREFIX=$home/src/comma/debian/tmp/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_PYTHON_PACKAGES=OFF \
    -DADD_PYTHON_PACKAGES_TO_RPM=OFF \
    -DBUILD_TESTS=OFF \
    -DINSTALL_BASH_COMPLETION=OFF \
    -DINSTALL_TESTS=OFF \
    -Dcomma_INSTALL_LIB_DIR=lib/x86_64-linux-gnu \
    -Dcomma_INSTALL_PACKAGE_DIR=lib/x86_64-linux-gnu/cmake/comma \
    -Dcomma_INSTALL_RUN_POST_INSTALL=OFF \
    -Dcomma_BUILD_XML=OFF \
    -Dcomma_BUILD_ZEROMQ=OFF \
    -Dcomma_build_io_rabbit_cat=OFF
make -j
sudo make install

mkdir -p $build_dir/debian/tmp/usr/lib
mkdir -p $build_dir/debian/tmp/DEBIAN

# Copy installed lib files, and debian configuration files to our build directory for packaging
cp -r $build_dir/lib/x86_64-linux-gnu $build_dir/debian/tmp/usr/lib
rsync -r $package_root/debian/* debian/

# Generate the control file
dpkg-gencontrol -pcomma

# Build the package
dpkg --build $build_dir/debian/tmp $build_dir
