#!/bin/bash

home=$1
[[ -n "$home" ]] || { echo "usage: $0 <packaging-dir>" >&2; exit 1; }
home=$( realpath $home )
mkdir -p $home/src
cd $home/src
git clone https://gitlab.com/orthographic/comma.git
build_dir=$home/src/comma/build
mkdir -p $build_dir
cd $build_dir

# if you want the library path to be lib/x86_64-linux-gnu
# see target build in src/comma/debian/rules
cmake $home/src/comma \
    -DCMAKE_INSTALL_PREFIX=$build_dir/debian/tmp/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_PYTHON_PACKAGES=OFF \
    -DADD_PYTHON_PACKAGES_TO_RPM=OFF \
    -DBUILD_TESTS=OFF \
    -DINSTALL_BASH_COMPLETION=OFF \
    -DINSTALL_TESTS=OFF \
    -Dcomma_INSTALL_RUN_POST_INSTALL=OFF \
    -Dcomma_BUILD_XML=OFF \
    -Dcomma_BUILD_ZEROMQ=OFF \
    -Dcomma_build_io_rabbit_cat=OFF
make -j
make install -j

# make vodoo debian directory
mkdir -p $build_dir/debian/tmp/DEBIAN

# copy debian configuration files to our build directory for packaging
cp -r $home/src/comma/debian/control $home/src/comma/debian/changelog $home/src/comma/debian/copyright $build_dir/debian

# generate the control file
dpkg-gencontrol -pcomma

# build the package
dpkg --build $build_dir/debian/tmp $build_dir
