#!/bin/bash

scriptname=$( readlink -f $0 )
source $( which comma-name-value-util ) || { echo "$scriptname: failed to source comma-name-value-util" >&2; exit 1; }

input="var_a=21
var_b=22"

echo -n "$input" | comma_path_mangle | gawk '{ print "output["NR-1"]="$0}'

