#!/bin/bash

source $( type -p comma-application-util ) || { echo "$0: failed to source comma-application-util" >&2 ; exit 1 ; }
source $( type -p comma-test-util ) || { echo "$0: failed to source comma-test-util" >&2 ; exit 1 ; }

output=$( comma_test_commands )
status=$?
echo "$output"
echo "status=$status"
echo "output/lines/count=$( wc -l <<< "$output" )"