#!/usr/bin/env python3

# Copyright (c) 2024 Vsevolod Vlaskine

import argparse, comma, json, os, sys

def _find( what, dir, absolute=False ):
    if dir == '-': raise Exception( 'comma-test-query: --dir="-": reading directories from stdin: todo, just ask' )
    real_root = os.path.realpath( dir )
    def _is_mount( p ): # quick and dirty, excessive and inefficient for now
        p = os.path.realpath( p )
        while not p in ['', '/']:
            if os.path.ismount( p ): return True
            p = os.path.dirname( p )
        return False
    def _valid( p ): # quick and dirty, inefficient for now
        if _is_mount( p ): return False
        while os.path.realpath( p ) != real_root:
            if os.path.isfile( f'{p}/{what}' ) or os.path.isfile( f'{p}/test' ): return True
            p = os.path.dirname( p )
        return False
    d = [ i[0] for i in os.walk( dir, followlinks=True ) ]
    root = d[0]
    r = sorted( filter( _valid, d ) )
    if not absolute: r = [ p[ ( len( root ) + 1 ) : ] for p in r ]
    return root, r

def _list( args ):
    _, paths = _find( args.what, args.dir, args.absolute )
    for p in paths: print( f'{p}' )

def _transpose( args ):
    _, paths = _find( args.what, args.dir )

def _traverse( args ):
    d = {}
    base, paths = _find( args.what, args.dir )
    for path in paths:
        what = f'{base}/{path}/{args.what}'
        status = 'todo'
        if os.path.isfile( what ):
            with open( what ) as f: comma.dictionary.set( d, path, json.load( f ) ) # todo: fix overfitting on loading files of various types
    json.dump( d, sys.stdout, indent = None if args.minify else 4 )

def make_args():
    description = 'usage: todo'
    epilog = 'examples: todo'
    parser = argparse.ArgumentParser( description=description, epilog=epilog, formatter_class=argparse.RawDescriptionHelpFormatter )
    parser.add_argument( '--dir', default='.', type=str, help='directory to traverse; default: current directory, "-": read paths from stdin (todo)' )
    parser.add_argument( '--verbose', '-v', help='more human-readable output', action='store_true' )
    subparsers = parser.add_subparsers( help='sub-command help' )
    list_parser = subparsers.add_parser( 'list', help='print subdirectories containing test or <what>, following symlinks, but skipping mounted drives (for now)' )
    list_parser.add_argument( 'what', type=str, choices=['readme.json'], help='output absolute path' )
    list_parser.add_argument( '--absolute', help='output absolute path', action='store_true' )
    list_parser.set_defaults( func=_list )
    transpose_parser = subparsers.add_parser( 'transpose', help='transpose into the given primary key' )
    transpose_parser.add_argument( 'what', type=str, choices=['readme.json'], help='output absolute path' )
    transpose_parser.add_argument( 'key', type=str, help='field name vs which to transpose' )
    transpose_parser.set_defaults( func=_transpose )
    traverse_parser = subparsers.add_parser( 'traverse', help='traverse subdirectories, following symlinks, find <what>, output combined json' )
    traverse_parser.add_argument( 'what', type=str, choices=['readme.json'], help='output absolute path' )
    traverse_parser.add_argument( '--minify', help='output one-line json', action='store_true' )
    traverse_parser.set_defaults( func=_traverse )
    return parser.parse_args()

def main():
    args = make_args()
    args.func( args )

if __name__ == '__main__': main()
