#!/bin/bash

# This file is part of comma, a generic and flexible library
# Copyright (c) 2014 The University of Sydney
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University of Sydney nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
# GRANTED BY THIS LICENSE.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
# HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

name=$( basename $0 )

source $( which comma-application-util ) 2>/dev/null || { echo "$name: could not source 'comma-application-util'" >&2; exit 1; }

function description()
{
    cat <<EOF
--help,-h; show this help
--accumulated; if present for --io, passed to iotop
--debug; much more debug output
--io; if present, run iotop instead of top
--output-fields; output the field names to stdout and exit
--num-procs=[<N>]; output the top N processes (default: totals)
--num-samples=[<N>]; number of samples to take, default: forever, until terminated
--sampling-interval,--delay=[<time>]; sampling interval, see '-d' option of top (1), default: defined by top (1)
--top-options=[<options>]; extra command line argument(s) pass to the top (1) utility
EOF
}

function usage()
{
    cat >&2 <<EOF
Invokes the performance monitoring utility top (1) or iotop in continuous mode, parses
top (1) output, and collects the results into CVS file (sent to stdout).

Usage: ${name} <options> [ > output_file.csv ]

Note: top (1) output is affected by its global and user configuration files.
There is no option to ignore those files. This utility assumes the default format
of top (1) output and will fail if alternative output layout is enforced through
the configuration file(s). It shall be possible to explicitly mandate the desired
output layout through command-line switches to top that override configuration
files. This is a possible future extension.

Options:
EOF
    description | sed 's/^/    /g' >&2
    cat >&2 <<EOF

Examples:

    Collect data until terminated by the user:

        $name > results.csv

    Take 1000 samples and quit (default sampling interval of top (1) is 3s; thus,
    collect 3000s of data):

        $name --num-samples=1000 > results.csv

    Facilitate parsing $name output:

        $name --output-fields

EOF
    exit 0
}

function feeder()
{
    local num=$1
    local extra_opts=$2
    local top_opts="-b $extra_opts"
    [[ -n "$num" ]] && top_opts="$top_opts -n $num"
    
    # make all buffering per-line
    stdbuf -oL -eL top $top_opts 
}

function extract_cpus()
{
    local input=$1
    local us=${input%% us, *}
    us=${us##%Cpu(s):*( )}
    local sy=${input%% sy, *}
    sy=${sy##* us,*( )}
    local total=$( echo "$us + $sy" | bc )
    echo -n "$us,$sy,$total"
}

function extract_mem()
{
    local input=$1
    local used=${input%% used*}
    used=${used##* *( )}
    echo -n ",$used"
}

function parser_totals()
{
    shopt -s extglob
    local timestamp line first shared
    first="true"
    grep --line-buffered -A 4 '^top' \
    | while true ; do
        read line
        [[ -z "$line" ]] && break
        [[ "$first" == "true" ]] && {
            shared=$( df --block-size=1024 --local 2>&1 | grep -v ": Permission denied" | grep '/shm$' | head -n 1 | gawk '{ print $3 }' )
            first="false"
        }
        [[ "$line" = "%Cpu(s)"* ]]  && extract_cpus "$line"
        [[ "$line" = "KiB Mem"* ]]  && { extract_mem  "$line" ; echo -n ",$shared" ; }
        # swap is last, finish the line
        [[ "$line" = "KiB Swap"* ]] && { extract_mem  "$line" ; echo ; }
        [[ "$line" = "--" ]] && first="true"
    done \
    | sed -u -n '1!p'
}

function parser_num_procs()
{
    grep --line-buffered -E -A $((num_procs + 1)) '^[ ]+PID ' \
    | sed -r -u -n 's/[[:blank:]]+/,/g ; s/^,// ; /^[0-9]+,/p'
}

io_payload_fields="total/read,total/write,actual/read,actual/write"
io_fields="timestamp,$io_payload_fields"
total_fields="timestamp,cpu/user,cpu/system,cpu/total,memory/ram,memory/shared,memory/swap"
procs_fields="timestamp,pid,user,priority,nice,memory/virtual,memory/physical,memory/shared,status,cpu/percent,memory/percent,uptime,command"

function output_fields()
{
    if (( $( comma_options_has --io $@ ) )) ; then echo $io_fields
    elif (( $(comma_options_has --num-procs $@ ) )); then echo $procs_fields
    else echo "$total_fields" ; fi
}

function run_iotop()
{
    local total actual
    [[ -z "$sampling_interval" ]] || delay="--delay=$sampling_interval"
    [[ -z "$accumulated" ]] || accumulated="--accumulated"
    sudo iotop --batch --kilobytes -o $delay $accumulated $top_options \
        | egrep -e 'Total DISK|Actual DISK' --line-buffered \
        | sed -u -e 's#[a-zA-Z:/ ]##g' -e 's/|/,/g' \
        | while read total ; do
              read actual || exit
              echo $total,$actual
          done \
        | csv-units --fields $io_payload_fields --scale 1024 \
        | csv-time-stamp 2>/dev/null
}

if (( $( comma_options_has --help "$@" ) || $( comma_options_has -h "$@" ) )) ; then usage ; exit ; fi
if (( $( comma_options_has --output-fields "$@" ) )) ; then output_fields "$@" ; exit ; fi

debug=0

description | comma-options-validate "$@"
comma_path_value_to_var --export < <( description | comma-options-to-name-value "$@" )

if [[ -n "$io" ]] ; then
    [[ -n "$( sudo which iotop )" ]] || { echo "comma-top: make sure iotop installed" >&2 ; exit 1 ; }
    run_iotop
else
    feeder_opts=""
    [[ -n "$sampling_interval" ]] && feeder_opts="-d $sampling_interval"
    [[ -n "$top_options" ]] && feeder_opts="$feeder_opts $top_options"
    [[ -n "$num_samples" && -z "$num_procs" ]] && (( ++num_samples )) # first line will be ignored, leaving num_samples lines
    if [[ -n "$num_procs" ]]; then parser="parser_num_procs"; else parser="parser_totals"; fi
    feeder "$num_samples" "$feeder_opts" "$num_procs" | $parser | csv-time-stamp 2>/dev/null 
fi
