#!/bin/bash

scriptname=$( basename "$0" )

function nonusage()
{
    cat >&2 <<EOF
$scriptname: shall be used from comma_env, do not call directly.
EOF
    exit 1
}

(( $# < 2 )) && nonusage
[[ "$1" == "-h" || "$1" == "--help" ]] && nonusage

[[ -f "$1" && $( basename "$1" ) == comma-env.* ]] && { source "$1" && rm -f "$1"; }
shift
$@
