#!/bin/bash

source $( which comma-application-util )

function output { local prefix=$1; gawk '{ print "'${prefix:+$prefix/}'output/line["NR-1"]="$0 }' ; }

function process_records
{
    local input_format=$1
    python3 -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 't,coordinates', 'datetime64[us]', point_t )
observer_t = comma.csv.struct( 'name,id', 'S3', 'uint32' )
record_t = comma.csv.struct( 'observer,event', observer_t, timestamped_point_t )
if "$input_format":
    format = ','.join(comma.csv.format.to_numpy("$input_format"))
else:
    format = ''
record_stream = comma.csv.stream( record_t, fields='dummy,y,z,name,id,t,x,,dummy', full_xpath=False, format=format )

for r in record_stream.iter():
  r['observer']['name'] = numpy.char.upper( r['observer']['name'] )
  r['event']['t'] += numpy.timedelta64( 1, 's' )
  r['event']['coordinates']['x'] -= 1
  record_stream.write( r )
END
)"
}

input_format='i,2d,s[3],ui,t,d,2ui'
output_format='s[3],ui,t,3d'

input=$( cat )
echo "$input" | process_records | output ascii
comma_status_ok
echo "ascii/status=$?"

echo "$input" | csv-to-bin $input_format | process_records $input_format | csv-from-bin $output_format | output binary
comma_status_ok
echo "binary/status=$?"

