#!/bin/bash

scriptname=$( basename $0 )

source $( type -p comma-process-util ) || exit 1
source $( type -p comma-application-util ) || exit 1

source $( type -p comma-test-util ) || exit 1

mkdir -p 'output/data' || exit 1
datadir="$( readlink -f 'output/data' )"
echo 'foo="bar"' > "$datadir/data.pv"

{
    comma_test_run_tarball '../data/path.tar' "--path=$datadir"
} | sed -e 's#^#path[0]/#g'
