#!/bin/bash
version=$1
comma_dir="$2"
[[ -n "$version" ]] || { echo "usage: $0 <ubuntu version> [<comma dir>]; e.g. $0 20.04" >&2; exit 1; }
[[ -n "$comma_dir" ]] || comma_dir=$( realpath ~/src/comma )
docker build -t ubuntu.$version.build.basics --build-arg version=$version --no-cache -f "$comma_dir/system/apt/Dockerfile" .
