#!/bin/bash

function die() { echo "$0: $@" >&2; exit 1; }

ubuntu_version="$1"
package="$2"
comma_dir="$3"
[[ -n "$package" ]] || { echo "usage: $0 <ubuntu version> <package> [<comma dir>]" >&2; exit 1; }
[[ -s "$package" ]] || die "file not found or empty: '$package'"
[[ -n "$comma_dir" ]] || comma_dir="$( realpath ~/src/comma )"
package_dir=$( dirname "$( realpath "$package" )" )

docker run \
       --mount "type=bind,source=$comma_dir,target=/mnt/comma" \
       --mount "type=bind,source=$package_dir,target=/mnt/package" \
       ubuntu.$ubuntu_version.build.basics \
       /mnt/comma/system/apt/comma-apt-package-test "/mnt/package/$( basename "$package" )" || { echo "$0: failed" >&2; exit 1; }
