#!/bin/bash

name=$( basename $0 )

python test_init.py || { echo "$name: init.py failed" >&2; exit 1; }
python test_format.py || { echo "$name: format.py failed" >&2; exit 1; }
python test_time.py || { echo "$name: time.py failed" >&2; exit 1; }
