#!/bin/bash

scriptname=$( basename "$0" )

source $( which comma-application-util ) || { echo "$scriptname: cannot source 'comma-application-util'" >&2; exit 1; }

output_dir="output"
mkdir -p "$output_dir" || { echo "$scriptname: cannot create directory '$output_dir'" >&2; exit 1; }

eval $( cat | comma_path_value_mangle | sed 's/^/input_/' )

if [[ -n "$input_files_direct" ]] ; then
    all_files=$( echo "$input_files_direct" | sed "s@-@$input_files_stdin@" )
else
    all_files=$input_files_stdin
fi

cat $input_files_stdin | csv-bin-cut $input_files_direct $input_command_line > "$output_dir/out.bin"
echo "status=$?"
cat "$output_dir/out.bin" | md5sum | cut -d' ' -f1 | sed 's/^/md5sum=/'
