#!/bin/bash

{ read options; read output_format; } < options

args=( $options )
format_index=$( echo $options | fmt -1 | grep -n -- '--binary' | cut -d: -f1 )
input_format="${args[$format_index]}"
[[ -z "$output_format" ]] && output_format=$input_format

csv-to-bin $input_format | csv-intervals make $options | csv-from-bin $output_format | gawk '{ printf( "interval[%d]=%s\n", NR, $0 ); }'
