#!/bin/bash

source $( type -p comma-application-util )

comma_path_value_to_var < <( cat )
eval "$input_cmd" \
    | csv-calc $operation $options \
    | name-value-from-csv --fields=$fields --prefix=output --line-number | tr -d '"'
