#! /usr/bin/env python
# -*- coding: utf-8 -*-
#/usr/bin/python2.4 -u

import commands # watch deprecated: see subprocess module doc
import unittest
import json

class name_value_calc_test( unittest.TestCase ) :
    def test_echo( self ):
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/small.json  data/large.json  --less --json" )[1], '1' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/mixed.json  data/medium.json --less --json" )[1], '0' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/medium.json data/mixed.json  --less --json" )[1], '0' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/medium.json data/large.json  --less --json" )[1], '1' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/large.json  data/medium.json --less --json" )[1], '0' )
    def test_strict( self ):
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/string1.pv  data/string2.pv  --sub" )[0], 0 )
        self.assertNotEqual( commands.getstatusoutput( "name-value-calc data/string1.pv  data/string2.pv  --sub  --strict" )[0], 0 )
    def test_exclude( self ):
        self.assertNotEqual( commands.getstatusoutput( "name-value-calc data/string1.pv  data/string2.pv  --sub  --strict" )[0], 0 )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/string1.pv  data/string2.pv  --sub  --strict --exclude 'bar'" )[0], 0 )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/string1.pv  data/string2.pv  --sub  --strict --exclude 'bar/'" )[0], 0 )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/string1.pv  data/string2.pv  --sub  --strict --exclude 'bar/baz'" )[0], 0 )
    def test_detailed( self ):
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/small.json  data/large.json  --less --json | wc -l" )[1], '1' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/small.json  data/large.json  --less --json  --detailed | wc -l" )[1], '10' )

unittest.main()
