#! /usr/bin/env python
# -*- coding: utf-8 -*-
#/usr/bin/python2.4 -u

import commands # watch deprecated: see subprocess module doc
import unittest
import json

class name_value_calc_test( unittest.TestCase ) :
    def test_less( self ):
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/small.json  data/large.json  --less --json --status" )[0], 0 )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/mixed.json  data/medium.json --less --json --status" )[0], 256 )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/medium.json data/mixed.json  --less --json --status" )[0], 256 )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/medium.json data/large.json  --less --json --status" )[0], 0 )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/large.json  data/medium.json --less --json --status" )[0], 256 )
    def test_echo( self ):
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/small.json  data/large.json  --less --json --echo" )[1], '1' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/mixed.json  data/medium.json --less --json --echo" )[1], '0' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/medium.json data/mixed.json  --less --json --echo" )[1], '0' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/medium.json data/large.json  --less --json --echo" )[1], '1' )
        self.assertEqual( commands.getstatusoutput( "name-value-calc data/large.json  data/medium.json --less --json --echo" )[1], '0' )

unittest.main()
