#!/bin/bash

source $( type -p comma-name-value-util )

# Strip leading and trailing white-space, comments and blank lines
test_input=$( sed -e 's/#.*//' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' | sed -n '/^[[:alnum:]]/p' )
comma_path_value_to_var < <( grep "=" <<< "$test_input" )

input=$( readlink -e $input )
bounding=$( readlink -e $bounding )

output_dir=output

[[ -d $output_dir ]] || mkdir $output_dir
cd $output_dir

stdin_first="-"
stdin_second=""
if [[ $bounds_first ]]; then
    stdin_first=""
    stdin_second="-"
fi

# note that we can't tell much conclusively about realtime streams,
# so we only output simple statistics

cat $input \
    | if [[ $input_type == "file" ]]; then
          csv-time-join $stdin_first $bounding $stdin_second $options --verbose
      else
          csv-play | csv-time-join $stdin_first <( sleep 0.01; cat $bounding | csv-play ) $stdin_second $options --verbose
      fi \
    | if [[ $options =~ --realtime ]]; then
          sed 's/[^,]//g' | wc -lc | tr -s ' ' | sed 's/^ //' | tr ' ' , \
              | csv-eval --fields=lines,chars "chars = chars / lines" \
              | name-value-from-csv -f num_records,num_fields
      else
          name-value-from-csv -f line -d : -n -p output
      fi
