#!/bin/bash

function usage()
{
    echo >&2
    echo "match input with expected values" >&2
    echo >&2
    echo "usage: cat some-test-output | aero-test-match <expected> [<options>]" >&2
    echo >&2
    echo "<expected>: file with expected outputs" >&2
    echo >&2
    exit 1
}

for arg in $@ ; do
    if [[ "$arg" == "--help" || "$arg" == "-h" ]] ; then usage ; fi
done

expected=$1

#todo

exit

