#!/bin/bash

source ./util || { echo "cannot source './util'" >&2; exit 1; }

function report_own_tree()
{
    echo "process tree of myself:" >&2
    pstree -a -c -g -l -p $main_pid >&2
}

children=()
background_launcher sleep 1 & children+=( $! )
background_launcher sleep 1 & children+=( $! )
background_launcher sleep 1 & children+=( $! )

main_pid=$BASHPID
verify_background_process_ids $main_pid "${children[@]}"
success=$?
(( success == 0 )) && echo "verification success" >&2

report_own_tree

(( success == 0 )) && wake_up ${children[@]} || wake_up_dead ${children[@]}

report_own_tree

echo "waiting for the children to terminate..." >&2
wait

exit $success
