#!/bin/bash

name=$( basename $0 )

default_vertex_fields="latitude,longitude,,id"
default_out_fields="first/latitude,first/longitude,second/latitude,second/longitude,first/id,second/id"

simple_usage()
{
    echo "Usage: $name [-h|--help] <vertices> <mesh> [-f|--fields=<vertex-fields>] [--of|--output-fields=<output-fields>" >&2
}

usage()
{
    simple_usage
    cat >&2 <<EOF

Extracts edges from a vertex file and a mesh file. Mesh files have the format: id1,id2.

Options:

    --help              Print help message.

    --fields            Specify vertex file fields (default: $default_vertex_fields)

    --output-fields     Specify output fields (default: $default_out_fields)

Example:

    $name vertices.csv mesh.csv --fields=latitude,longitude,id --output-fields=first/latitude,first/longitude,first/id,second/latitude,second/longitude,second/id

EOF
}

if [[ $# == 0 ]]; then
    simple_usage
    exit 1
fi

vert=
mesh=
fields=
out_fields="$default_out_fields"

while [[ $# -gt 0 ]]; do
    case "$1" in
    -h|--help)
        usage
        exit 0
        ;;
    -f=*|--fields=*)
        fields=${1#*=}
        ;;
    --of=*|--output-fields=*)
        out_fields=${1#*=}
        ;;
    -*)
        echo "$name: unrecognized option '$1'" >&2
        exit 1
        ;;
    *)  if [[ -z "$vert" ]]; then
            vert="$1"
        elif [[ -z "$mesh" ]]; then
            mesh="$1"
        else
            usage
            exit 1
        fi
    esac
    shift
done

if [[ -z "$mesh" ]]; then
    simple_usage
    exit 1
fi

if [[ -z "$fields" ]]; then
    cmd=( cat )
else
    cmd=( csv-shuffle --fields="$fields" --output-fields="$default_vertex_fields" )
fi

( cat "$vert" | "${cmd[@]}" ; echo "---"; cat "$mesh" ) | awk -F, '
BEGIN { m = n = 0; }
/^---$/ { m = 1; next; }

m == 0 { lat[$4] = $1; lon[$4] = $2; next; }
m == 1 \
{
    if (!($1 in lat)) { print "mesh-to-edges: error: id " $1 " not found" | "cat >&2"; exit; }
    if (!($2 in lat)) { print "mesh-to-edges: error: id " $2 " not found" | "cat >&2"; exit; }
    print lat[$1] "," lon[$1] "," lat[$2] "," lon[$2] "," $1 "," $2;
}
' | csv-shuffle --fields="$default_out_fields" --output-fields="$out_fields"
