#!/bin/bash

scriptname=$( basename "$0" )

source $( which comma-application-util ) || { echo "$scriptname: cannot source 'comma-application-util'" >&2; exit 1; }

output_dir="output"
mkdir -p "$output_dir" || { echo "$scriptname: cannot create directory '$output_dir'" >&2; exit 1; }

comma_path_value_to_var

if [[ -n "$input_files_direct" ]] ; then
    all_files=$( echo "$input_files_direct" | sed "s@-@$input_files_stdin@" )
else
    all_files=$input_files_stdin
fi

function compare()
{
    local fields="$1"
    local subdir=$2
    mkdir -p "$output_dir/$subdir" || { echo "$scriptname: cannot create directory '$output_dir/$subdir'" >&2; return 1; }
    local cut_args="--binary=$input_binary --fields=$fields"
    local shuffle_output_fields=$( echo "$input_fields" | cut -d, -f${fields} )
    local shuffle_args="--binary=$input_binary --fields=$input_fields --output-fields=$shuffle_output_fields"
    cat $input_files_stdin | csv-bin-cut $input_files_direct $cut_args > "$output_dir/$subdir/new.bin" || return 1
    cat $all_files | csv-shuffle $shuffle_args > "$output_dir/$subdir/old.bin" || return 1
    cmp "$output_dir/$subdir/new.bin" "$output_dir/$subdir/old.bin" > "$output_dir/$subdir/cmp.log"
}

compare "1" "1"
echo "one/field/first/cmp/status=$?"

compare "3" "2"
echo "one/field/third/cmp/status=$?"

compare "5" "3"
echo "one/field/last/cmp/status=$?"

compare "1,3" "4"
echo "two/fields/expanded/cmp/status=$?"

compare "1,3" "5"
echo "two/fields/collapsed/cmp/status=$?"
