#!/bin/bash

name=$( basename $0 )

function handle()
{
    [[ -n "$workdir" ]] && rm -rf "$workdir"
}

trap 'handle' EXIT

output_dir="output"
mkdir -p "$output_dir" || exit 1
output_dir=$( readlink -f "$output_dir" )

tarball="../data/resources.tar"
[[ -r "$tarball" ]] || {
    echo "$name: file '$tarball' not found" >&2
    exit 1
}
tarball=$( readlink -f "$tarball" )

workdir=$( mktemp --directory --tmpdir="$output_dir" )
cd "$workdir"
tar xf "$tarball" || exit 1
cd resources || exit 1

comma-test-run --raw --max-memory-main=5000 --max-memory-shared=6000 --max-parallel=10 > "$output_dir/comma-test-run.log"
(( $? == 0 )) || exit 1

cat "stats/progress.csv" \
    | csv-time --fields=time,, --to seconds \
    | csv-shuffle --fields=time,name,stage --output-fields=name,stage,time \
    | sed 's@^./@@' \
    | name-value-from-csv number,stage,time --indices=number,stage --no-brackets --prefix=test \
    | sed 's@/@[@;s@/@]/@;s@"@@g'  # want to bracket number but not stage; no quotes
