#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

event_t = comma.csv.struct( 'time,point', 'datetime64[us]', '3f8' )
record_t = comma.csv.struct( 'observer,event', 'S3', event_t )

fields = ',event/point,observer,,event/time,,'
format = 'i4,3f8,S3,S7,datetime64[us],u4,u4'
record_stream = comma.csv.stream( record_t, fields=fields, format=format )

for i,r in enumerate( record_stream.iter( size=1 ), start=1 ):
  r['observer'] = numpy.char.upper( r['observer'] )
  r['event']['time'] += numpy.timedelta64( i, 's' )
  r['event']['point'] += [i,-1,-2]
  record_stream.write( r )
END
)"
}

csv-to-bin i,3d,s[3],s[7],t,2ui | process_records | csv-from-bin s[3],t,3d | output
comma_status_ok
echo "status=$?"
