#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )

fields = ',event/coordinates/y,event/coordinates/z,observer,,event/time,event/coordinates/x,,'
format = 'int32,float64,float64,S3,S7,datetime64[us],float64,uint32,uint32'
record_stream = comma.csv.stream( record_t, fields=fields, format=format )

record_stream.read( size=1 ) # skip one line
r = record_stream.read( size=2 )
r['observer'][1] = numpy.char.upper( r['observer'][1] )
r['event']['time'][1] += numpy.timedelta64( 1, 's' )
r['event']['coordinates']['x'][1] += 1
record_stream.write( r )
END
)"
}

csv-to-bin i,2d,s[3],s[7],t,d,2ui | process_records | csv-from-bin s[3],t,3d | output
comma_status_ok
echo "status=$?"
