#!/bin/bash

source $( which comma-process-util ) || exit 1
source "../detail/common-functions" || exit 1
source "../detail/tests23-functions" || exit 1

export output_dir="output"
mkdir -p "$output_dir" || exit 1

export output_file="$output_dir/test02.log"
function test02()
{
    comma_execute_and_wait --max-wait=20 "bash -c test_to_execute 5 4"
}
test02
echo "test[2]/exit/status=$?"
[[ -f "$output_file" ]] && cat "$output_file" | uniq -c | sed 's@^ *@test[2]/output="@;s@$@"@'
