#!/bin/bash

source $( type -p comma-application-util ) || { echo "$0: failed to source comma-application-util" >&2 ; exit 1 ; }
source $( type -p comma-test-util ) || { echo "$0: failed to source comma-test-util" >&2 ; exit 1 ; }

comma_test_interactive_commands
result=$?

echo "bad/syntax/test/output=\"this test was skipped because it doesnt match expected syntax\""
echo "bad/syntax/test/status=0"
if (( result != 0 )); then 
    echo "this/test/shouldnt/run/output=\"this test did not run\""
    echo "this/test/shouldnt/run/status=0"
fi