#!/bin/bash

source $( which comma-application-util )

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )

fields = ',event/coordinates/y,event/coordinates/z,observer,,event/time,event/coordinates/x,,'
format = 'i,2d,s[3],s[7],t,d,ui,ui,f'
record_stream = comma.csv.stream( record_t, fields=fields, format=format )
END
)"
}

output="$( csv-to-bin i,2d,s[3],s[7],t,d,2ui | process_records | csv-from-bin s[3],t,3d; comma_status_ok )"
status=$?
echo "output=$output"
echo "status=$status"
