#!/bin/bash

readonly scriptname=$( basename "$0" )

util="comma-process-util"
source $( which "$util" ) || { echo "cannot source '$util'" >&2; exit 1; }

function report_own_tree()
{
    echo "process tree of main:"
    pstree -a -c -g -l -p $main_pid
}

export main_pid=$BASHPID
echo "main is PID $main_pid" >&2

fifo=$( mktemp --dry-run )
trap "rm -f '$fifo'" EXIT
mkfifo "$fifo" || { echo "$scriptname: cannot create FIFO '$fifo'" >&2; exit 1; }
echo "$scriptname: use fifo '$fifo'" >&2

children=()
for n in {1..3} ; do
    builtin echo "$scriptname: attempt to start a background process..." >&2
    comma_process_exec "$fifo" sleep 1 & last_child=$!
    builtin echo "$scriptname: launched background child '$last_child', now verify..." >&2
    comma_process_validate "$fifo" $last_child || { pkill -TERM -P $main_pid; wait; exit 1; }
    children+=( $last_child )
done

report_own_tree >&2

echo "waiting for the children to terminate..." >&2
wait
