#!/bin/bash

export PATH="$(pwd)/bin:$PATH"

function list_known_signals_on_one_line()
{
    eval "${@}" | tr '\n' ',' | head -c -1
    return ${PIPESTATUS[0]}
}
export -f list_known_signals_on_one_line

source $( which comma-test-util ) || { echo "$0: failed to source comma-test-util" >&2 ; exit 1 ; }

comma_test_commands
