#!/bin/bash

function default_values
{
    python -c "$( cat <<END
import comma

comma.csv.time.zone( 'UTC' )

point_t = comma.csv.struct( 'id,signal,x,y,z', 'uint64', '(2,)float64', 'float64', 'float64', 'int64' )
observer_t = comma.csv.struct( 't,id', 'datetime64[us]', 'uint8' )
record_t = comma.csv.struct( 'name,point,observer', 'S3', point_t, observer_t )
default_values = { 'point/signal': (-111, -222), 'point/y': 123, 'observer/t': '19991212T123456' }
stream = comma.csv.stream( record_t, binary=True, default_values=default_values, verbose=True)
stream.write( stream.read() )
END
)"
}

output=$( csv-to-bin s[3],ul,4d,l,t,ub | default_values | csv-from-bin s[3],ul,4d,l,t,ub )
status=$?
echo "$output" | csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'
echo "status=$status"
