#!/bin/bash

source $( which comma-application-util )

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
event_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )

fields = ',coordinates/y,coordinates/z,,,time,coordinates/x,,'
input_stream = comma.csv.stream( event_t, fields=fields )

output_t = comma.csv.struct( 'norm,flag', 'float64', 'uint32' )
output_stream = comma.csv.stream( output_t, binary=False, tied=input_stream )

for events in input_stream.iter():
  output = numpy.empty( input_stream.size, dtype=output_t )
  output['norm'] = numpy.linalg.norm( events['coordinates'].view( '3f8' ), axis=1 )
  output['sum'] = 1
  output_stream.write( output )
END
)"
}

output="$( process_records )"
status=$?
echo "$output" | cut -d, -f1-9 | csv-paste value="original/line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'
echo "$output" | cut -d, -f10-11 | csv-paste value="appended/line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'

echo "status=$status"
