#!/bin/bash

source $( which comma-application-util )

function process_records
{
    python -c "$( cat <<END
import comma
import numpy
import sys

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
event_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )

fields = ',coordinates/y,coordinates/z,,,time,coordinates/x,,'
input_stream = comma.csv.stream( event_t, fields=fields )

output_t = comma.csv.struct( 'max,flag', 'float64', 'uint32' )
output_stream = comma.csv.stream( output_t, binary=False, tied=input_stream )

for events in input_stream.iter():
  output = numpy.empty( events.size, dtype=output_t )
  output['max'] = numpy.max( events['coordinates'].view( '3f8' ), axis=1 )
  output['flag'] = [1,2,3]
  output_stream.write( output )
END
)"
}

output="$( process_records )"
status=$?
echo "$output" | csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'

echo "status=$status"
