#!/bin/bash

cd output
echo | io-tee out "some_illegal_command" > /dev/null
status=$?
echo "test: output status of io-tee: $status" >&2
if [[ $status != 0 ]]; then
    echo "illegal_command/failed=\"true\""
else
    echo "illegal_command/failed=\"false\""
fi
