#!/bin/bash
in=$(cat )
echo $in | name-value-convert --from xml --to json --indented >output/json
diff -w output/json expected-json
#read from unkown
echo $in | name-value-convert --to json --indented >output/out2
diff -w output/out2 expected-json
