#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

event_t = comma.csv.struct( 'point,time', '(3,)f8', '(2,)datetime64[us]' )
record_t = comma.csv.struct( 'observer,event', 'S3', event_t )

record_stream = comma.csv.stream( record_t, format=','.join( record_t.types ) )

for i,r in enumerate( record_stream.iter( size=1 ), start=1 ):
  r['observer'] = numpy.char.upper( r['observer'] )
  r['event']['time'] += numpy.timedelta64( i, 's' )
  r['event']['point'] += [i,-1,-2]
  record_stream.write( r )
END
)"
}

csv-to-bin s[3],3d,2t | process_records | csv-from-bin s[3],3d,2t | output
comma_status_ok
echo "status=$?"
