#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
event_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )

fields = ',coordinates/y,coordinates/z,,,time,coordinates/x,,'
format = ','.join( comma.csv.format.to_numpy( 'i,d,d,s[3],s[7],t,d,ui,ui' ) )
input_stream = comma.csv.stream( event_t, fields=fields, format=format )

output_t = comma.csv.struct( 'max', 'float64' )
output_stream = comma.csv.stream( output_t, binary=True, tied=input_stream )

for events in input_stream.iter():
  output = numpy.max( events['coordinates'].view( '3f8' ), axis=1 ).view( output_t )
  output_stream.write( output )
END
)"
}

format="i,2d,s[3],s[7],t,d,2ui"
csv-to-bin $format | process_records | csv-from-bin $format,d | output
comma_status_ok
echo "status=$?"
