#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
event_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )

fields = ',coordinates/y,coordinates/z,,,time,coordinates/x,,'
input_stream = comma.csv.stream( event_t, fields=fields )

output_t = comma.csv.struct( 'max', 'float64' )
output_stream = comma.csv.stream( output_t, tied=input_stream )

for events in input_stream.iter():
  output = numpy.max( events['coordinates'].view( '3f8' ), axis=1 ).view( output_t )
  events['coordinates']['x'] += 1
  output_stream.write( output )
END
)"
}

process_records | output
comma_status_ok
echo "status=$?"
