#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y', 'float64', 'float64' )
stream = comma.csv.stream( point_t, fields='x,name,y', format='f8,S3,f8'  )

for points in stream.iter():
  # changes below should not affect dump as it uses internal buffers
  points['x'] = points['x'] + 1
  points['y'] = points['y'] + 1
  stream.dump()
END
)"
}

csv-to-bin d,s[3],d | process_records | csv-from-bin d,s[3],d | output
comma_status_ok
echo "status=$?"
