#!/bin/bash

function say() { echo "usage: $0: $@" >&2; }; function die() { say "$@"; exit 1; }

add-apt-repository -y ppa:orthographic/ppa || die "add-apt-repository ppa:orthographic/ppa failed"
add-apt-repository -y multiverse || die "add-apt-repository multiverse failed"
apt-get update || die "apt-get update failed"
apt-get -y install comma || die "apt-get install comma failed"

say "testing basic csv utilities..."
output=$( csv-paste line-number | head | csv-to-bin ui | csv-from-bin ui ) || die "failed: failed to run"
expected=$( seq 0 9 )
[[ "$output" == "$expected" ]] || die "failed: unexpected output: $output"
say "testing basic csv utilities: done"

say "testing bash utils..."
type -p comma-application-util || die "failed: failed"
say "testing bash utils: done"

say "running csv-eval --help (for reference): todo"
#csv-eval --help

# todo
say "testing csv-eval: todo"
#output=$( seq 0 9 | csv-eval --fields a "a+=1" || exit ) || die "failed: failed to run"
#expected=$( seq 1 10 )
#[[ "$output" == "$expected" ]] || die "failed: unexpected output: $output"
#say "testing csv-eval: done"
