#!/bin/bash

# todo
#   - manual steps (automate if possible)
#     - update changelog
#       - version
#       - changes
#       - date
#     - cmake: update default version
#     - commit
#     - tag repo with version
#     - push

type -p debuild >/dev/null || sudo apt install devscripts
function say() { echo "usage: $0: $@" >&2; }; function die() { say "$@"; exit 1; }
[[ -n "$2" ]] || { echo "usage: $0 <what> <ubuntu-name> <comma-version>" >&2; exit 1; }
what=$1
comma_version=$2
name=comma_${comma_version}
[[ -d comma ]] || die "comma directory not found; please run in something like ~/src"
tar -acf $name.orig.tar.gz comma || die "tar failed"
if [[ "$what" == "orig" ]]; then rm -f comma/debian/files; what_option='a'
elif [[ "$what" == "update" ]]; then what_option='d'
else die "expected <what>: orig or update; got \"$what\""; fi
( cd comma && debuild -S -s$what_option ) || die "debuild failed"
dput ppa:orthographic/comma $name-0ppa0_source.changes || die "dput failed"
