#!/bin/bash

source $( which comma-process-util ) || exit 1
source "../detail/common-functions" || exit 1

export output_dir="output"
mkdir -p "$output_dir" || exit 1

function test01()
{
    export script=$( dirname "$0" )/../detail/tester
    [[ -x "$script" ]] || exit 1

    local output_dir="$output_dir/test01"
    rm -rf "$output_dir" || exit 1
    mkdir -p "$output_dir" || exit 1

    commandlist=( "$script 10 $output_dir/log1" "$script 5 $output_dir/log2" )

    # This is a template for running multiple background commands in parallel
    for c in "${commandlist[@]}" ; do echo $c ; done |
       (
           xargs -I{} --max-procs 0 bash -c '
              {
                  comma_execute_and_wait "{}"
              }' 
       )
    # end of template

    [[ -s "$output_dir/log1" ]] || exit 1
    [[ -s "$output_dir/log2" ]] || exit 1

    is_parallel=$( verify_parallel "$output_dir" )
    echo "test[1]/parallel=$is_parallel"
}

test01
echo "test[1]/exit/status=$?"
