#!/bin/bash

name=$( basename $0 )

source $( type -p comma-test-util ) || exit 1

mkdir -p 'output' || exit 1

result="$( comma_test_run_tarball '../data/sample.tar' )"
output_directory="$( name-value-get --from path-value 'output_directory' <<< "$result" )"

elapsed="$output_directory/stats/elapsed.csv"
[[ -r "$elapsed" ]] || { echo "Could not access '$elapsed'" >&2 ; exit 1 ; }
cat "$elapsed" | sed 's@^\./@@'

exit 0
