#!/bin/bash

name=$( basename $0 )

source "../common-functions" || exit 1

function handle()
{
    [[ -n "$workdir" ]] && rm -rf "$workdir"
}

trap 'handle' EXIT

output_dir="output"
rm -rf "$output_dir" || exit 1
mkdir -p "$output_dir" || exit 1
output_dir=$( readlink -f "$output_dir" )

tarball="../data/sample.tar"
[[ -f "$tarball" ]] || {
    echo "$name: file '$tarball' not found" >&2
    exit 1
}
tarball=$( readlink -f "$tarball" )

workdir=$( mktemp --directory )
cd "$workdir"
tar xf "$tarball" || exit 1
cd sample || exit 1
comma-test-run --raw $@ > "$output_dir/log" 2>&1
(( $? == 0 )) || exit 1

cat "$output_dir/log" | sed '1d;$d' | format_tests_per_directory
exit $?
