#!/bin/bash

scriptname="comma_bash_application_test_2"

source $( which comma-application-util ) || { printf "%s could not source comma-application-util" $scriptname >&2 ; exit 1 ; } 

mkdir -p output

declare -i count=0
while read -r line ; do
    comma_path_value_to_var <<< "$line" && echo "line[$count]/status=1" || echo "line[$count]/status=0" 
    (( ++count ))
done

for f in 1 2 3 4 ; do
    [[ -f "output/security_hole_$f" ]] && echo "security_hole[$f]=1" || echo "security_hole[$f]=0"
done

