---
# sample ansible-playbook script to install comma dependencies and build comma from source; include it as it is or copy to your playbook

- hosts: localhost
  connection: local
  vars:
    - base: "{{ ansible_env.HOME }}"
    - make_j: 6
    - comma_cmake_options: "-DBUILD_TESTS=ON -DINSTALL_TESTS=ON -DINSTALL_BASH_COMPLETION=ON -Dcomma_BUILD_XML=ON -Dcomma_BUILD_ZEROMQ=ON -Dcomma_INSTALL_WEB_SHELL=OFF -DPYTHON=/usr/bin/python3"
    - build_in_src: false
    - src_dir: "{{ base }}/src/comma"
    - build_dir: "{{ src_dir + '/build' if build_in_src else base + '/build/comma' }}"

  tasks:
  - name: 'set variables'
    set_fact:
      ubuntu_greater_than_2204: "{{ ansible_distribution_version is version('22.04', '>') }}"
      pip_break_system_packages: "{{ '--break-system-packages' if ubuntu_greater_than_2204 else '' }}"
      lib_proc: "{{ 'libproc2-dev' if ubuntu_greater_than_2204 else 'libprocps-dev' }}"
  
  - name: "install comma dependencies"
    become: true
    apt:
        pkg: ['build-essential', 'git', 'cmake-curses-gui', 'cmake', 'gawk', 'perl', 'python3', 'libboost-all-dev', 'socat', 'libzmq3-dev', 'libgtest-dev', 'python3-dev', 'python3-pip', 'python3-numpy', "{{ lib_proc }}", 'libyaml-dev', 'recode']
        state: present
        update_cache: yes

  - name: "install comma regressions test dependencies"
    become: true
    apt:
        pkg: ['moreutils', 'net-tools', 'pv']
        state: present
        update_cache: yes

  - name: "comma: make source directory {{ src_dir }}"
    file: dest="{{ src_dir }}" state=directory

  - name: "comma: clone"
    git:
        repo: "https://gitlab.com/orthographic/comma.git"
        dest: "{{ src_dir }}"
        clone: yes
        update: yes

  - name: "comma: make build directory {{ build_dir }}"
    file: dest="{{ build_dir }}" state=directory

  - name: "comma: cmake"
    vars:
        - comma_cmake_options: "-DBUILD_TESTS=ON -DINSTALL_TESTS=ON -DINSTALL_BASH_COMPLETION=ON -Dcomma_BUILD_XML=ON -Dcomma_BUILD_ZEROMQ=ON -DBUILD_PYTHON_PACKAGES=ON -Dcomma_INSTALL_WEB_SHELL=OFF -DPYTHON=/usr/bin/python3"
    shell: "/usr/bin/cmake {{ comma_cmake_options }} {{ src_dir }} chdir={{ build_dir }}"

  - name: "comma: make"
    make:
        chdir: "{{ build_dir }}"
        params:
            MAKEFLAGS: "-j {{ make_j }}"

  - name: "comma: install"
    become: true
    make:
        chdir: "{{ build_dir }}"
        target: "install"
