#!/bin/bash

function format_incorrect_name { python -c "import comma; point_t = comma.csv.struct( 'x', 'invalid' )"; }
function format_empty_name { python -c "import comma; point_t = comma.csv.struct( 'x', '' )"; }
function format_incorrect_number { python -c "import comma; point_t = comma.csv.struct( 'x,y', 'float64' )"; }

function basic
{
    python -c "$( cat <<END
import numpy
import comma

data_t = comma.csv.struct( 'x,id', numpy.float64, numpy.uint32 )
data_t = comma.csv.struct( 'x,id', 'float64', 'uint32' )
data_t = comma.csv.struct( 'x,id', 'f8', 'u4' )
data_t = comma.csv.struct( 't', 'datetime64[us]' )
data_t = comma.csv.struct( 'name', 'S10' )
END
)"
}

function format_None { python -c "import comma; point_t = comma.csv.struct( 'x', None ); print point_t.format"; }

function record
{
    local what=$1
    python -c "$( cat <<END
import comma

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 't,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )
print record_t.$what
END
)"
}

function struct_get
{
    local what=$1
    python -c "$( cat <<END
import comma

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 't,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event,id', 'S3', timestamped_point_t, 'uint32' )
print ','.join( comma.csv.struct.get( '$1', record_t.dtype, 'root/' ) )
END
)"
}


format_incorrect_name; echo "format_incorrect_name/status=$?"
format_empty_name; echo "format_empty_name/status=$?"
format_incorrect_number; echo "format_incorrect_number/status=$?"

basic; echo "basic/status=$?"

output=$( format_None )
status=$?
echo "format_None/output=$output"
echo "format_None/status=$status"

for what in fields format; do
    output=$( record $what )
    status=$?
    echo "record/$what/output=$output"
    echo "record/$what/status=$status"
done

for what in fields format; do
    output=$( struct_get $what )
    status=$?
    echo "struct_get/$what/output=$output"
    echo "struct_get/$what/status=$status"
done
