#!/bin/bash

function missing_field
{
    python -c "$( cat <<END
import comma

comma.csv.time.zone( 'UTC' )

point_t = comma.csv.struct( 'id,signal,x,y,z', 'uint64', '(2,)float32', 'float64', 'float64', 'int64' )
observer_t = comma.csv.struct( 't,id', 'datetime64[us]', 'uint8' )
record_t = comma.csv.struct( 'name,point,observer', 'S3', point_t, observer_t )
stream = comma.csv.stream( record_t, fields=',observer/id,point/x,point/z,,' )
stream.write( stream.read() )
END
)"
}

output=$( missing_field )
status=$?
echo "$output" | csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'
echo "status=$status"
