#!/bin/bash

function missing_field
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )
record_stream = comma.csv.stream( record_t, fields=',event/coordinates/y,event/coordinates/z,observer,,event/time,,,' )
END
)"
}

output=$( missing_field )
status=$?
echo "output=$output"
echo "status=$status"
