#!/bin/bash

. input

data=$( grep -v ^$ <<< "$data" )

[[ $append ]] && append_option="--append=$append"

output_fields=$( csv-repeat --output-fields --fields=data $append_option )
output_format=$( csv-repeat --output-format --binary=$format $append_option )

time_fields=t,$( csv-fields clear --except time <<< $output_fields )

for mode in ascii binary; do

    now=$( echo "1" | csv-time-stamp | csv-shuffle --fields=t, --output-fields=t | csv-time --to seconds )

    csv_eval_expr="t-=$now"
    [[ $append =~ time ]] && csv_eval_expr+="; time-=$now"

    while IFS=, read data pause; do
        echo $data
        sleep $pause
    done <<< "$data" \
        | if [[ $mode == "binary" ]]; then
              csv-to-bin $format --flush \
                  | csv-repeat --timeout=$timeout --period=$period $append_option --binary=$format \
                  | csv-from-bin $output_format --flush
          else
              csv-repeat --timeout=$timeout --period=$period $append_option
          fi \
        | csv-time-stamp | csv-time --fields $time_fields --to seconds \
        | csv-eval --fields=$time_fields "$csv_eval_expr" --flush \
        | name-value-from-csv --fields=timestamp,$output_fields --line-number --prefix=$mode \
        | csv-quote -d = --unquote

done
