#!/bin/bash

. input

data=$( grep -v ^$ <<< "$data" )

[[ $append ]] && append_option="--append=$append"
[[ $period ]] && period_option="--period=$period"

output_fields=$( csv-repeat --output-fields --fields=data $append_option )
output_format=$( csv-repeat --output-format --binary=$format $append_option )

time_fields=t,$( csv-fields clear --except time <<< $output_fields )

for mode in ascii binary; do

    csv_eval_expr="t-=init_t"
    [[ $append =~ time ]] && csv_eval_expr+="; time-=init_t"

    while IFS=, read data pause; do
        echo $data
        sleep $pause
    done <<< "$data" \
        | if [[ $mode == "binary" ]]; then
              csv-to-bin $format --flush \
                  | csv-repeat --timeout=$timeout $period_option $append_option --binary=$format \
                  | csv-from-bin $output_format --flush
          else
              csv-repeat --timeout=$timeout $period_option $append_option
          fi \
        | csv-time-stamp | csv-time --fields $time_fields --to seconds \
        | gawk 'BEGIN { FS="," } { if( init_t == 0 ) init_t=$1; print $0,init_t }' OFS=, \
        | csv-eval --fields=$time_fields,init_t "$csv_eval_expr" --flush \
        | name-value-from-csv --fields=timestamp,$output_fields --line-number --prefix=$mode \
        | csv-quote -d = --unquote

done
