#!/bin/bash

source $( which comma-application-util )

function process_records
{
    python3 -c "$( cat <<END
from __future__ import print_function
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )
record_stream = comma.csv.stream( record_t )

try:
    for r in record_stream.iter( size=-1 ):
        pass
except ValueError:
    print( "exception=ValueError" )
END
)"
}


process_records
