#!/bin/bash

source $( which comma-application-util )

function output { local prefix=$1; gawk '{ print "'${prefix:+$prefix/}'output/line["NR-1"]="$0 }' ; }

function process_records
{
    local binary
    if [[ "$1" == "binary" ]]; then binary=True; else binary=False; fi
    python3 -c "$( cat <<END
import comma
import numpy

event_t = comma.csv.struct( 'point,time', '(3,)f8', '(2,)datetime64[us]' )
record_t = comma.csv.struct( 'observer,event', 'S3', event_t )

record_stream = comma.csv.stream( record_t, binary=$binary )

for i,r in enumerate( record_stream.iter( size=1 ), start=1 ):
  r['observer'] = numpy.char.upper( r['observer'] )
  r['event']['time'] += numpy.timedelta64( i, 's' )
  r['event']['point'] += [i,-1,-2]
  record_stream.write( r )
END
)"
}

input=$( cat )
echo "$input" | process_records | output ascii
comma_status_ok
echo "ascii/status=$?"

echo "$input" | csv-to-bin s[3],3d,2t | process_records binary | csv-from-bin s[3],3d,2t | output binary
comma_status_ok
echo "binary/status=$?"

