#!/bin/bash

source $( which comma-name-value-util )

count=0
while read line args; do
    echo "$line" | comma_path_value_line_split $args | gawk '{ print "test["'$count'"]/result[" NR - 1 "]=\"" $0 "\""; }'
    (( ++count ))
done
