#!/bin/bash
name=$( basename $0 )
version=$1
comma_dir="$2"
[[ -n "$version" ]] || { echo -e "usage: $name <ubuntu version> [<comma dir>]\n e.g. $name 20.04" >&2; exit 1; }
[[ -n "$comma_dir" ]] || comma_dir=$( realpath ~/src/comma )
[[ -d "$comma_dir" ]] || { echo "usage: $name please specify <comma dir> explicitly (since you seem to either run with sudo or have comma not in '$comma_dir')" >&2; exit 1; }

echo "$name: running:" >&2
docker build -t ubuntu.$version.build.comma --build-arg version=$version -f "$comma_dir/system/package/cpack/Dockerfile" .
