#!/bin/bash
name=$( basename $0 )
ubuntu_version=$1
comma_version=$2
comma_dir="$3"
[[ -n "$comma_version" ]] || { echo "usage: $name <ubuntu version> <comma version> [<comma dir>]" >&2; exit 1; }
[[ -n "$comma_dir" ]] || comma_dir="$( realpath ~/src/comma )"
[[ -d "$comma_dir" ]] || { echo "usage: $name please specify <comma dir> explicitly (since you seem to either run with sudo or have comma not in '$comma_dir')" >&2; exit 1; }

echo "$name: running:" >&2
docker run --rm \
       --mount "type=bind,source=$comma_dir,target=/mnt/comma" \
       --mount "type=bind,source=$( pwd ),target=/root/output" \
       ubuntu.$ubuntu_version.build.comma \
       /mnt/comma/system/package/cpack/comma-package-make $ubuntu_version $comma_version /mnt/comma || { echo "$name: failed" >&2; exit 1; }
