#!/bin/bash

name=$( basename $0 )
function die() { echo "$name: $@" >&2; exit 1; }

ubuntu_version=$1
comma_version=$2
comma_dir="$3"
package_name="comma-$comma_version-ubuntu-$ubuntu_version"
[[ -n "$comma_dir" ]] || comma_dir=$( realpath ~/src/comma )
[[ -n "$comma_version" ]] || { echo "usage: $name <ubuntu version> <comma version> [<comma dir>]" >&2; exit 1; }

(
    mkdir -p ~/build/comma
    cd ~/build/comma
    echo "$name: running cmake in $( pwd )..." >&2
    cmake $comma_dir \
            -Dcomma_version="$comma_version" \
            -DCPACK_GENERATOR=DEB \
            -DBUILD_PYTHON_PACKAGES=OFF \
            -DADD_PYTHON_PACKAGES_TO_RPM=OFF \
            -DBUILD_SHARED_LIBS=ON \
            -DBUILD_TESTS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DINSTALL_BASH_COMPLETION=OFF \
            -DINSTALL_TESTS=OFF \
            -DCPACK_DEBIAN_FILE_NAME="$package_name.deb" \
            -Dcomma_BUILD_XML=OFF \
            -Dcomma_build_io_rabbit_cat=OFF || die "cmake failed"
    echo "$name: running make in $( pwd )..." >&2
    make -j$(nproc) || die "make failed"
    echo "$name: running make install in $( pwd )..." >&2
    make install || die "make install failed"
    echo "$name: running cpack in $( pwd )..." >&2
    cpack -j$(nproc) || die "cpack failed"
    echo "$name: created package at $( realpath $package_name.deb )" >&2
    # todo: optionally run full regression test
    echo "$name: done" >&2
)
if [[ -d /root/output/ ]]; then
    cp ~/build/comma/$package_name.deb /root/output/ || die "copy output failed"
    echo "$name: copied $( realpath ~/build/comma/$package_name.deb ) to $( realpath output )" >&2
fi

# (
#     cd ~/src/comma/python
#     echo "$0: setting up python in $( pwd )" >&2
#     #python3 setup.py --command-packages=stdeb.command bdist_deb || die "failed"
#     echo "$0: running python3 setup.py ..." >&2
#     python3 setup.py --command-packages=stdeb.command sdist_dsc --copyright-file ../COPYING --suite focal  || die "failed"
#     # todo: mount gpg key
#     # debsign -k 79BF9724F37751A39B08698DB3CB85AF5FB6E9F1 deb_dist/comma-py_1.0.0-1.dsc
#     # mkdir tmp
#     # cd tmp
#     # dpkg-source -x ../deb_dist/comma-py_1.0.0-1.dsc
#     # cd comma-py-1.0.0
#     # debuild -S -sa
#     # dput ppa:orthographic/ppa ../comma-py_1.0.0-1_source.changes
#     # ? debsign -k 79BF9724F37751A39B08698DB3CB85AF5FB6E9F1 ../../deb_dist/comma-py_1.0.0-1_source.changes
#     #
#     # ...
#     echo "$0: building package..." >&2
#     cd deb_dist/comma-$version_major.$version_minor.$version_patch || die "failed"
#     dpkg-buildpackage -rfakeroot -uc -us || die "failed"
#     #https://shallowsky.com/blog/programming/packaging-launchpad-ppas.html
#     # todo? or do all above outside of this script using something like (but also see above):
#     #       debsigs --sign=origin -k 79BF9724F37751A39B08698DB3CB85AF5FB6E9F1 comma-1.0.0-Linux.deb
#     cd ~/build/comma
#     echo "$0: running cmake in $( pwd )" >&2
#     cmake . -DCPACK_GENERATOR=DEB \
#             -DBUILD_PYTHON_PACKAGES=ON \
#             -DADD_PYTHON_PACKAGES_TO_RPM=OFF \
#             -DBUILD_SHARED_LIBS=ON \
#             -DBUILD_TESTS=OFF \
#             -DCMAKE_BUILD_TYPE=Release \
#             -DCMAKE_INSTALL_PREFIX=/usr \
#             -DINSTALL_BASH_COMPLETION=OFF \
#             -DINSTALL_TESTS=OFF \
#             -DCPACK_DEPENDENCIES_LIBPROCPS="$libproc_version" \
#             -DCPACK_PACKAGE_VERSION_MAJOR=$version_major \
#             -DCPACK_PACKAGE_VERSION_MINOR=$version_minor \
#             -DCPACK_PACKAGE_VERSION_PATCH=$version_patch  \
#             -Dcomma_INSTALL_LIB_DIR=lib/x86_64-linux-gnu \
#             -Dcomma_BUILD_XML=OFF \
#             -Dcomma_build_io_rabbit_cat=OFF || die "failed"
#     echo "$0: running cpack in $( pwd )" >&2
#     cpack || die "failed"
#     # todo: optionally run full regression test
#     echo "$0: done" >&2
# )
# cp ~/build/comma/comma-$version_major.$version_minor.$version_patch-Linux.deb output
# cp ~/src/comma/python/deb_dist/comma-py*.deb output
