#!/bin/bash

cat stdin | csv-play | csv-time-join <( sleep 0.01; cat filter | csv-play ) --verbose | name-value-from-csv -f line -d : -n -p lower
cat stdin | csv-play | csv-time-join <( sleep 0.01; cat filter | csv-play ) --by-upper --verbose | name-value-from-csv -f line -d : -n -p upper
cat stdin | csv-play | csv-time-join <( sleep 0.01; cat filter | csv-play ) --nearest --verbose | name-value-from-csv -f line -d : -n -p nearest
cat stdin | csv-play | csv-time-join <( sleep 0.01; cat filter | csv-play ) --nearest --bound=0.02 --verbose | name-value-from-csv -f line -d : -n -p bounds_nearest
cat stdin | csv-play | csv-time-join <( sleep 0.01; cat filter | csv-play ) --by-lower --bound=0.02 --verbose | name-value-from-csv -f line -d : -n -p bounds_lower
cat stdin | csv-play | csv-time-join <( sleep 0.01; cat filter | csv-play ) --by-upper --bound=0.02 --verbose | name-value-from-csv -f line -d : -n -p bounds_upper
