#!/bin/bash

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

t = comma.csv.struct( 't', 'datetime64[us]' )
s = comma.csv.stream( t )

for r in s.iter( size=1 ):
  s.write( r )
END
)"
}

output="$( process_records )"
status=$?
echo "$output" | csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'
echo "status=$status"

