#!/bin/bash

[ -n "$comma_util_test_test_run_black_subdirs_common_include_guard_" ] && return || readonly comma_util_test_test_run_black_subdirs_common_include_guard_=1

# this is EXIT handler; purpose:
# - shall never leave all those test subdirs behind
# - still want them left behind for post-mortem
function post_test()
{
    trap '' INT TERM PIPE QUIT HUP
    dir=$1
    rm -rf ".$1"
    mv "$1" ".$1"
}
export -f post_test
