#!/bin/bash

source $( which comma-process-util )

function f1()
{
    trap 'f5' EXIT
    echo "1"
}

function f2()
{
    # trap -p has format: trap -- 'commands...'
    original_exit_trap_cmd="$( trap -p | grep 'EXIT$' )"

    # insert a call to f3 after the first single quote
    local new_exit_trap_cmd=$( echo "$original_exit_trap_cmd" | sed "s/^[^']*'/&f3\;/g" )
    eval "$new_exit_trap_cmd"
    trap f3 RETURN
    echo "2"

    exit 1
}

function f3()
{
    eval "$original_exit_trap_cmd"
    echo "3"
    trap - RETURN
}

function f4()
{
    echo "4"
}

function f5()
{
    echo "5"
}

f1
f2
f4

