#!/bin/bash

source $( type -p comma-process-util )

scriptname=$( basename "$0" )

function usage()
{
    cat >&2 <<EOF

runs the provided command under comma_execute_and_wait

rationale: to ensure that processes launched by the command are terminated

example: $scriptname comma-nap 1

EOF
    exit 1
}

(( $# == 0 )) && usage
command="bash -c eval \"$@\""
comma_execute_and_wait --group "$command"
