#!/bin/bash

source $( which comma-process-util )

scriptname=$( basename "$0" )

function usage()
{
    cat >&2 <<EOF
$scriptname: runs the provided command under comma_execute_and_wait
EOF
    exit 1
}

(( $# == 0 )) && usage
command="bash -c eval \"$@\""
comma_execute_and_wait --group "$command"
