#!/bin/bash

scriptname=$( basename "$0" )

source $( which comma-string-util ) || { echo "$scriptname: cannot source 'comma-string-util'" >&2; exit 1; }

function nonusage()
{
    cat >&2 <<EOF
$scriptname: shall be used from comma_env, do not call directly.
EOF
    exit 1
}

[[ $# == 0 || "$1" == "-h" || "$1" == "--help" ]] && nonusage

eval "$comma_env_environment"

command_to_execute="$@"
cmd=$( shopt -s extglob ; cmd=${command_to_execute##*( )bash*( )-c*( )}; echo "$cmd" )
if [[ "$cmd" != "$command_to_execute" ]] ; then
    exec bash -c "$cmd"
else
    exec $@
fi
