#!/bin/bash

scriptname=$( basename "$0" )

function nonusage()
{
    cat >&2 <<EOF
$scriptname: shall be used from comma_env, do not call directly.
EOF
    exit 1
}

[[ $# == 0 || "$1" == "-h" || "$1" == "--help" ]] && nonusage

eval "$comma_env_environment"
$@
