#!/bin/bash

function missing_field
{
    python -c "$( cat <<END
import comma

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
stream = comma.csv.stream( point_t, fields='z,x' )
stream.write( stream.read() )
END
)"
}

output=$( missing_field )
status=$?
echo "$output" | csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'
echo "status=$status"
