#!/bin/bash

function names_only()
{
    gawk -F '=' '! /^[0-9A-Z_a-z]+=/ {exit} {print $1}'
}

# assume a reasonably empty environment
echo "----- printenv -----" >&2
printenv >&2
echo "printenv/count=$( printenv | names_only | wc -l )"
echo "----- set -----" >&2
set >&2
echo "set/count=$( set | wc -l )"

testdir=$( dirname "$0" )
scriptname=$( basename "$testdir" )/$( basename "$0" )

function protect_main_env()
{
    (
        source $( which comma-env-util ) || exit 1
        allvars=$( comma_env --default-imports ) || {
            echo "$scriptname: 'comma_env --default-imports' failed" >&2
            exit 1
        }
        echo "$allvars"
    )
}

allvars=$( protect_main_env ) || exit 1
for varname in ${allvars//,/ } PATH ; do
    echo -n "$varname/defined="
    [[ -v $varname ]] && echo '"yes"' || echo '"no"'
done
