#!/bin/bash

source $( which comma-application-util )

function output { local prefix=$1; gawk '{ print "'${prefix:+$prefix/}'output/line["NR-1"]="$0 }' ; }

function default_values
{
    local input_format=$1
    python -c "$( cat <<END
import comma

comma.csv.time.zone( 'UTC' )

point_t = comma.csv.struct( 'id,signal,x,y,z', 'uint64', '(2,)float64', 'float64', 'float64', 'int64' )
observer_t = comma.csv.struct( 't,id', 'datetime64[us]', 'uint8' )
record_t = comma.csv.struct( 'name,point,observer', 'S3', point_t, observer_t )
default_values = { 'point/signal': (-111, -222), 'point/y': 123, 'observer/t': '19991212T123456' }
stream = comma.csv.stream( record_t, binary=bool("$input_format"), default_values=default_values, verbose=True)
stream.write( stream.read() )
END
)"
}

input_format='s[3],ul,4d,l,t,ub'
output_format='s[3],ul,4d,l,t,ub'

input=$( cat )
echo "$input" | default_values | output ascii
comma_status_ok
echo "ascii/status=$?"

echo "$input" | csv-to-bin $input_format | default_values $input_format | csv-from-bin $output_format | output binary
comma_status_ok
echo "binary/status=$?"

