#!/bin/bash

function numpy_format_from_comma { python -c "import comma; print comma.csv.numpy_format_from_comma( '$1' )"; }

while read name comma_format; do
    output=$( numpy_format_from_comma $comma_format )
    status=$?
    echo "$name/output=$output"
    echo "$name/status=$status"
done
