#!/bin/bash

function comma_time_roundabout {
    python3 -c "$( cat <<END
from __future__ import print_function
import numpy
import comma

comma_time = '$@'
numpy_time = comma.csv.time.to_numpy( comma_time )
if isinstance( numpy_time, numpy.datetime64 ):
  print( comma.csv.time.from_numpy( numpy_time ) )
END
)"
}

while read name time; do
    output=$( comma_time_roundabout $time )
    status=$?
    echo "$name/output=$output"
    echo "$name/status=$status"
done
