#!/bin/bash

scriptname=$( basename "$0" )
scriptdir=$( dirname "$0" )

output_dir="output"
mkdir -p "$output_dir" || exit 1

source $( which comma-env-util ) || { echo "$scriptname: cannot source 'comma-env-util'" >&2; exit 1; }
[[ -x $( which comma-env-detail ) ]] || { echo "$scriptname: cannot find executable 'comma-env-detail'" >&2; exit 1; }

app="$scriptdir/bin/app"
[[ -x "$app" ]] || { echo "$scriptname: cannot find executable '$app'" >&2; exit 1; }

export PATH="$( pwd )/bin:$PATH"
export TMPDIR="$output_dir"

log="${output_dir}/log"
comma_env --default app > "$log"

function format_names()
{
    tr ',' '\n' \
        | sort \
        | name-value-from-csv --output-line-number name \
        | sed 's@^@variable@'
}

{

    comma_env --default-imports | format_names | sed 's@^@default/@'

    echo "PWD,SHLVL,_" | format_names | sed 's@^@ignore/@'

    cat "$log" \
        | cut -d= -f1 \
        | sort \
        | name-value-from-csv --output-line-number name \
        | sed 's@^@child/variable@'
} \
    | sed 's@/name=@=@'
