#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
event_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )

input_stream = comma.csv.stream( event_t, binary=True )

output_t = comma.csv.struct( 'max', 'float64' )
output_stream = comma.csv.stream( output_t, binary=True, tied=input_stream )

for events in input_stream.iter():
  output = numpy.max( events['coordinates'].view( '3f8' ), axis=1 ).view( output_t )
  events['coordinates']['z'] += 1
  output_stream.write( output )
END
)"
}

format="t,3d"
csv-to-bin $format | process_records | csv-from-bin $format,d | output
comma_status_ok
echo "status=$?"
