#!/bin/bash

source $( which comma-application-util )

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )
record_stream = comma.csv.stream( record_t, fields='event,observer', format='datetime64[us],float64,float64,float64,S3' )

for i,r in enumerate( record_stream.iter(), start=1 ):
  r['observer'] = numpy.char.upper( r['observer'] )
  r['event']['time'] += numpy.timedelta64( i, 's' )
  r['event']['coordinates']['x'] += i
  record_stream.write( r )
END
)"
}

output="$( csv-to-bin t,3d,s[3] | process_records | csv-from-bin s[3],t,3d; comma_status_ok )"
status=$?
echo "$output" | csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'
echo "status=$status"

