#!/bin/bash

function handle_usr1()
{
    trap '' SIGTERM SIGHUP SIGPIPE SIGINT SIGUSR1
    exit 12
}

trap 'handle_usr1' SIGUSR1

exec 1> "$output_file"
comma_execute_and_wait "bash -c test02_to_execute" --signals=TERM,HUP,USR1
