#!/bin/bash

# This file is part of comma, a generic and flexible library
# Copyright (c) 2011 The University of Sydney
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#    This product includes software developed by the University of Sydney.
# 4. Neither the name of the University of Sydney nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
# GRANTED BY THIS LICENSE.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
# HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# @author Mathew Hounsell

_comma_opts()
{
    cat <<EOF
--binary
--delimiter
--fields
--flush
--full-xpath
--help
--output-fields
--precision
--quote
--verbose
EOF
#--output
}

_comma_test_run_opts() 
{
    cat <<EOF
--begin
--black-list
--debug
--dry-run
--end
--from
--help
--max-memory-main
--max-memory-shared
--max-parallel
--max-run-time
--max-wait-time
--no-ansiterm-control-characters
--no-control-characters
--optional
--output-directories
--parallel
--path
--quiet
--raw
--run-disabled
--run-optional
--test-option
--to
--until-first-failure
--verbose
--white-list
EOF
}

_csv_time_opts()
{
    cat <<EOF
--delimiter
--fields
--from
--iso
--sec
--to
--to-iso-string
--to-seconds
aixm
iso
seconds
sql
EOF
}

_csv_shuffle_opts()
{
_comma_opts
    cat <<EOF
append
remove
swap
EOF
}

_csv_update_opts()
{
    cat <<EOF
--empty
--erase
--format
--help
--last
--last-only
--matched-only
--remove
--reset
--unset
--update-non-empty-fields
--verbose
ascii
binary
EOF
}

_simple()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=$( $1 )
 
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}

_comma_test_run() { _simple _comma_test_run_opts ; }
_csv_shuffle() { _simple _csv_shuffle_opts ; }
_csv_time() { _simple _csv_time_opts ; }
_csv_update() { _simple _csv_update_opts ; }

complete -F _comma_test_run comma-test-run
complete -F _csv_shuffle csv-shuffle
complete -F _csv_time csv-time
complete -F _csv_update csv-update

# todo
#     - add --bash-completion to csv-units, csv-update, comma-test-_comma_test_run
#     - install in the installation directory, if possible (if not, /etc is OK)

_comma_bash_completion()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=$( ${COMP_WORDS[0]} --bash-completion )
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
}

complete -F _comma_bash_completion csv-units
