#!/bin/bash

scriptname=$( basename "$0" )
scriptdir=$( dirname "$0" )

output_dir="output"
mkdir -p "$output_dir" || exit 1

source $( which comma-env-util ) || { echo "$scriptname: cannot source 'comma-env-util'" >&2; exit 1; }
[[ -x $( which comma-env-detail ) ]] || { echo "$scriptname: cannot find executable 'comma-env-detail'" >&2; exit 1; }

app="$scriptdir/bin/app"
[[ -x "$app" ]] || { echo "$scriptname: cannot find executable '$app'" >&2; exit 1; }

export PATH="$( pwd )/bin:$PATH"
export TMPDIR="$output_dir"

function abracadabra()
{
    echo "dummy"
}
export -f abracadabra

result=$( abracadabra )
funcname="abracadabra"
echo "parent/abracadabra/status=$?"
echo "parent/abracadabra/result=$result"

comma_env --import=$funcname app
