#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function process_records
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,mask', 'float64', 'float64', 'uint32' )
stream = comma.csv.stream( point_t, fields='x,name,y,mask', format='f8,S3,f8,u4'  )

for points in stream.iter(size=3):
  # changes below should not affect dump as it uses internal buffers
  points['x'] = points['x'] + 1
  points['y'] = points['y'] + 1
  mask = points['mask'].astype('bool')
  stream.dump(mask=mask)
END
)"
}

csv-to-bin d,s[3],d,ui | process_records | csv-from-bin d,s[3],d,ui | output
comma_status_ok
echo "status=$?"
