#!/usr/bin/python

import numpy
import comma
import sys

point = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point = comma.csv.struct( 't,point', 'datetime64[us]', point )
data = comma.csv.struct( 'designator,attributes', 'S3', timestamped_point )

#s = comma.csv.fields.stream( data, fields=',attributes/point/z,attributes/point/y,,,attributes/t,attributes/point/x,designator', format='i4,d,d,u1,u1,datetime64[us],d,S3' )
#s = comma.csv.fields.stream( data, fields=',attributes/point/z,attributes/point/y,,,attributes/t,attributes/point/x,designator', format='i,d,d,ub,ub,t,d,s[3]', is_comma_format=True )
s = comma.csv.stream( data, fields=',attributes/point/z,attributes/point/y,,,attributes/t,attributes/point/x,designator' )

j = 0
#for i in s.iter( recarray=False ):
  #i['designator'] = 'AAA'
  #i['attributes']['t'] += numpy.timedelta64( 5, 's' )
  #i['attributes']['point']['x'] += 0
  #i['attributes']['point']['y'] += 1
  #i['attributes']['point']['z'] += 2

for i in s.iter( size=1 ):
  i.designator = 'AAA'
  j += 1
  i.attributes.t += numpy.timedelta64( j, 's' )
  i.attributes.point.x += 0
  i.attributes.point.y += 1
  i.attributes.point.z += 2
  s.write( i )
