#!/bin/bash

#  rationale:
#      io-tee-worker on ubuntu 16.04 fails to work with exported bash functions
#      due to a bug in bash 4.3.42 and/or lunux function popen()
#      the wrapper passes exported functions in the bash environment to io-tee-worker
#      hence enabling io-tee-worker to use user-defined bash functions

declare -i file_and_options_end=1 # file is the required first argument of io-tee-worker, so if -- is not present, 1 is the correct index value

for(( i = 1; i <= $#; i++ )); do
    if [[ "${!i}" == "--" ]]; then
        file_and_options_end=i
        break
    fi
done

file_and_options=( "${@:1:$file_and_options_end}" )
command="${@:$(( file_and_options_end + 1 )):1}"
command_args=( "${@:$(( file_and_options_end + 2 ))}" )

functions="$( declare -fx )"

io-tee-worker "${file_and_options[@]}" "$functions ${functions:+;} $command" "${command_args[@]}"
