#!/bin/bash

scriptname=$( basename $0 )

source $( type -p comma-application-util ) || { echo "io-topics: could not source 'comma-application-util'" >&2; exit 1; }
source $( type -p comma-process-util ) || { echo "io-topics: could not source 'comma-process-util'" >&2; exit 1; }

# todo: --master-config: default behaviour: first config; --guess-by command: all configs

function description()
{
    cat <<EOF
--help,-h; display help and exit
--config=[<config>]; <config>: <dir>[:<path>], where <dir> is path to a json or path-value file specifying topic attributes, <path>: path inside config, multiple --config options allowed, configs will be applied in the reverse order of --config options on command line (see examples)
--dry-run,--dry; print final command and exit
--topics-from-all-configs,--all; take topics from all configs, default: take topics only from the first config ("master config")
--topic-fields; output topic config fields and exit
--topic-fields-help; output topic config fields help and exit
--verbose,-v; print verbose information
EOF
}

function usage()
{
    cat >&2 <<eof
    
a simple topic publisher supporting tcp, local sockets, and zero-mq (i.e. whatever io-publish supports)

usage: io-topics <operation> [<topics>] <options>

todo: debug zero-mq support

operations
    cat: receive and handle data on given topics
    
    list: list topics
    
    log: log topics (todo)
    
    publish: start all the publishers listed on command line or in the config file (todo)

options
$( description | sed 's/^/    /g' )

examples
    publish
        run publisher with topics a and b, with b on demand
            > io-topics publish --config <( echo "a/command=csv-paste line-number"; echo "a/port=8888"; echo "b/command=csv-paste line-number"; echo "b/port=9999"; echo "b/on_demand=1" )
            io-topics: will run 'comma_execute_and_wait --group' with commands:
            io-topics:     io-publish tcp:8888   -- csv-paste line-number
            io-topics:     io-publish tcp:9999  --on-demand -- csv-paste line-number
        
        in a different shell, observe that topic a keeps running even if no-one is listening, whereas topic b runs only if at least one client is connected:
            > socat tcp:localhost:8888 | head -n5 # will output something like:
            16648534
            16648535
            16648536
            16648537
            16648538
            
            > socat tcp:localhost:9999 - | head -n5
            0
            1
            2
            3
            4
            
    cat
        run publisher
            > io-topics publish --config <( echo "a/command=csv-paste line-number"; echo "a/port=8888"; echo "b/command=csv-paste line-number"; echo "b/port=9999"; echo "b/on_demand=1" )
        
        in a different shell, run clients
            > io-topics cat --config <( echo "a/command=head -n5 > a.csv"; echo "a/address=tcp:localhost:8888"; echo "b/command=head -n5 > b.csv"; echo "b/address=tcp:localhost:9999" )
            
        check output
            > cat a.csv 
            203740462
            203740463
            203740464
            203740465
            203740466
            > cat b.csv 
            0
            1
            2
            3
            4

eof
    exit 0
}

function say() { if [[ -n "$operation" ]]; then echo "io-topics: $operation: $@"; else echo "io-topics: $@"; fi >&2; }
function verbose() { (( options_verbose )) && say "$@"; }
function warning() { say "warning: $1"; }
function die() { say "$@"; exit 1; }

function list_topic_fields() { :; }

function publish_topic_fields()
{
    cat <<eof
address
binary
command
on_demand
port
size
eof
}

function publish_topic_fields_help()
{
    cat <<eof
address; if present, passed verbatim to io-publish, in this case port attribute ignored
binary; if publisher publishes binary data, the binary format of the data, overrides size
command; command for the publisher to run
on_demand; if present, same meaning as io-publish --on-demand
port; tcp port for publishing, unless address field is present
size; if publisher publishes binary data, size of the binary record, if no binary attribute given
eof
}

function cat_topic_fields()
{
    cat <<eof
address
binary
command
flush
host
port
size
eof
}

function cat_topic_fields_help()
{
    cat <<eof
address; if present, passed verbatim to io-publish, in this case port attribute ignored
binary; if data is binary, the binary format of the data, overrides size
command; command for the client to run
flush; flush output on each record, default: buffer output
host; tcp host for publishing, unless address field is present
port; tcp port for publishing, unless address field is present
size; if if data is binary, size of the binary record, if no binary attribute given
eof
}

function log_topic_fields()
{
    cat <<eof
address
binary
command
dir
flush
host
index
path
period
port
restart
size
suffix
eof
}

function log_topic_fields_help()
{
    cat <<eof
address; if present, passed verbatim to io-publish, in this case port attribute ignored
binary; if data is binary, the binary format of the data, overrides size
command; optional command for the logger to run instead of default logger
dir; log directory, for each <topic>, actual log directory will be [<path>/]<dir>/<topic>
flush; flush output on each record, default: buffer output
host; tcp host for publishing, unless address field is present
index; optional command to generate index file, default: fixed-width binary index for each binary record, ascii: no index file
path; prefix path for log directory (e.g. if logs need to be split across multiple drives)
period; split log files on a given number of seconds
port; tcp port for publishing, unless address field is present
restart; if data stream disconnects keep trying to reconnect
size; if if data is binary, size of the binary record, if no binary attribute given
suffix; optional log file suffix, default: bin for binary, csv for ascii
eof
}

function publish_command()
{
    [[ -n "$topic_address" || -n "$topic_port" ]] || die "neither address nor port specified for topic '$topic' in files ${configs[@]}"
    [[ -n "$topic_address" ]] || topic_address="tcp:$topic_port"
    if [[ -n "$topic_on_demand" ]]; then on_demand="--on-demand"; else unset on_demand; fi
    local cmd="io-publish $topic_address $size_option $on_demand -- $topic_command"
    verbose "$cmd"
    echo "$cmd"
}

function cat_command()
{
    [[ -n "$topic_address" || ( -n "$topic_host" && -n "$topic_port" ) ]] || die "neither address nor host/port specified for topic '$topic' in files ${configs[@]}"
    [[ -n "$topic_address" ]] || topic_address="tcp:$topic_host:$topic_port"
    if [[ -n "$topic_on_demand" ]]; then on_demand="--on-demand"; else unset on_demand; fi
    if [[ -n "$topic_flush" ]]; then flush_option="--flush"; else unset flush_option; fi # todo! make flush default?!
    local cmd="bash -c io-cat $topic_address $size_option $flush_option | $topic_command" # todo? comma_execute_and_wait?
    verbose "$cmd"
    echo "$cmd"
}

function log_run()
{
    local address="$1"
    local command="$2"
    local index="$3"
    local period="$4"
    local csv_split_options="$5"
    local path="$6"
    local flush_option="$7"
    local restart="$8"
    cd $path
    while [[ -z $SHUTDOWN ]] ; do
        if [[ $command ]]; then
            bash -c "$command"
        else
            io-cat $address $flush_option | $index | csv-split -t $period $csv_split_options $flush_option
        fi
        (( restart )) || break
        sleep 0.1
    done
}

export -f log_run

function log_command()
{
    die "todo"
}

function cat_config()
{
    local name path
    IFS=: read name path <<< "$1"
    if [[ -z "$path" ]]; then cat $name; else cat $name | name-value-convert | grep "^$path/" | sed "s#$path/##"; fi
}

function topics_from_config() # quick and dirty
{
    if [[ -n "$options_topics_from_all_configs" ]]; then egrep -e "/address=|/port=" <<< "$config" | cut -d= -f1 | sed -e 's#/address$##' -e 's#/port$##' | uniq; return; fi
    grep '=""' <<< "$master_config" | cut -d= -f1
    for path in $( grep -v '=""' <<< "$master_config" | cut -d= -f1 ); do dirname $path; done | uniq
}

function read_configs()
{
    configs=( $( grep "=" <<< "$options" | grep "^config=" | cut -d= -f2 | sed 's#"##g' | tac ) )
    (( ${#configs[@]} > 0 )) || die "please specify at least one config"
    master_config=$( cat_config ${configs[-1]} ) # quick and dirty
    config=$( { for c in ${configs[@]}; do cat_config $c; done; echo "$master_config"; } | name-value-convert ) # quick and dirty
}

function get_topics()
{
    topics=( ${unnamed[@]:1} )
    if (( ${#topics[@]} == 0 )); then topics=( $( topics_from_config ) ); fi
    (( ${#topics[@]} > 0 )) || die "no topics in config files ${configs[@]}"
}

(( $( comma_options_has --help "$@" ) || $( comma_options_has -h "$@" ) )) && usage
options="$( description | comma-options-to-name-value "$@"; comma_status_ok )" || die "invalid options"
unnamed=( $( grep -v "=" <<< "$options" | sed 's#"##g' ) )
operation=${unnamed[0]}
[[ $( type -t ${operation}_topic_fields ) == "function" ]] || die "expected operation, got '$operation'" # quick and dirty
eval "$( grep "=" <<< "$options" | comma_path_value_mangle | sed 's#^#options_#' )"
[[ -z "$options_topic_fields" ]] || { ${operation}_topic_fields; exit 0; }
[[ -z "$options_topic_fields_help" ]] || { ${operation}_topic_fields_help; exit 0; }
read_configs
get_topics
if [[ $operation == "list" ]]; then for topic in ${topics[@]}; do echo $topic; done; exit; fi
commands=()
for topic in ${topics[@]}; do
    eval "$( ${operation}_topic_fields | sed 's#^#unset topic_#' )" # todo: quick and dirty, watch performance
    eval "$( grep $topic <<< "$config" | sed "s#^$topic/#topic/#" | comma_path_value_mangle )"
    [[ -n "$topic_command" ]] || die "command not specified for topic '$topic' in files ${configs[@]}"
    if [[ -n "$topic_binary" ]]; then size_option="--size $( csv-size $topic_binary )"
    elif [[ -n "$topic_size" ]]; then size_option="--size $topic_size"
    else unset size_option; fi
    cmd="$( ${operation}_command )" || die "on topic $topic: making command failed"
    commands+=( "$cmd" )
done
say "will run 'comma_execute_and_wait --group' with commands:"
for cmd in "${commands[@]}"; do say "    $cmd"; done
[[ -z "$options_dry_run" ]] || exit
comma_execute_and_wait --group "${commands[@]}"
