#!/bin/bash

function usage()
{
    echo "io-tee wrapper that can be used with exported functions in bash" >&2
}


declare -i counter=0

for arg in "$@"; do
    case "$arg" in
        -h|--help) usage; exit ;;
        --) break ;;
        *) (( counter++ )) ;;
    esac
done

if (( counter < $#  )); then
    file_and_options=( "${@:1:$((counter+1))}" )
    command="${@:$((counter+2)):1}"
    command_args=( "${@:$((counter+3))}" )
else
    file_and_options=( "$1" )
    command="$2"
    command_args=( "${@:3}" )
fi

echo " > file_and_options: ${file_and_options[@]}" >&2
echo " > command: $command" >&2
echo " > command_args: ${command_args[@]}" >&2
echo >&2

all_functions="$( declare -f )"
io-tee "${file_and_options[@]}" "$all_functions; $command" "${command_args[@]}"
