#!/bin/bash

# This file is part of comma, a generic and flexible library
# Copyright (c) 2011 The University of Sydney
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University of Sydney nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
# GRANTED BY THIS LICENSE.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
# HOLDERS AND CONTRIBUTORS \"AS IS\" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

function usage()
{
    echo "publish data on tcp in a packet-based manner"
    echo "zero-publish <packet-size> <tcp-port>"
    echo
    exit 1
}


function stop
{
    pids=$( ps -eo ppid:1,pid:1 | grep "^$$" | cut -f2 -d' ' )
    for pid in $pids ; do kill -9 $pid &> /dev/null ; done
}

function bye
{
    is_shutdown="true"
    stop
    exit 1
}

trap bye INT TERM HUP

for ARG in $@ ; do
    if [[ "$ARG" == "--help" || "$ARG" == "-h" ]] ; then usage ; fi
done

SIZE=$1
TCP_PORT=$2

if [[ -z $SIZE || -z $TCP_PORT ]]; then
    echo "zero-publish: please specify size and port"
    exit 1
fi

SOCKET="/tmp/zero-publish-$TCP_PORT"
echo " size $SIZE socket $SOCKET"
cat | zero-cat -b 16 -s $SIZE --publish ipc://$SOCKET &
socat -U tcp4-listen:$TCP_PORT,reuseaddr,fork exec:"zero-cat -b 16 'ipc://$SOCKET' --size $SIZE" 2>/dev/null &

while [[ -z $is_shutdown ]] ; do
    sleep 0.5
done

stop

