#!/bin/bash

function usage()
{
    echo "publish data on tcp in a packet-based manner"
    echo "zero-publish <packet-size> <tcp-port>"
    echo
    exit 1
}


function stop
{
    pids=$( ps -eo ppid:1,pid:1 | grep "^$$" | cut -f2 -d' ' )
    for pid in $pids ; do kill -9 $pid &> /dev/null ; done
}

function bye
{
    is_shutdown="true"
    stop
    exit 1
}

trap bye INT TERM HUP

for ARG in $@ ; do
    if [[ "$ARG" == "--help" || "$ARG" == "-h" ]] ; then usage ; fi
done

SIZE=$1
TCP_PORT=$2

if [[ -z $SIZE || -z $TCP_PORT ]]; then
    echo "zero-publish: please specify size and port"
    exit 1
fi

SOCKET="/tmp/zero-publish-$TCP_PORT"
echo " size $SIZE socket $SOCKET"
cat | zero-cat -s $SIZE --publish ipc://$SOCKET &
socat -U tcp4-listen:$TCP_PORT,reuseaddr,fork exec:"zero-cat 'ipc://$SOCKET' --size $SIZE" 2>/dev/null &

while [[ -z $is_shutdown ]] ; do
    sleep 0.5
done

stop

