#!/bin/bash

testdir=$( dirname "$0" )
scriptname=$( basename "$testdir" )/$( basename "$0" )

source $( which comma-env-util ) || exit 1

function frobnicate()
{
    echo 'frobnicate/called="yes"'
    echo "frobnicate/argument=\"$1\""
}
export -f frobnicate

function frobnicate_wrapper()
{
    echo 'frobnicate/wrapper/called="yes"'
    frobnicate "$foobar"
}
export -f frobnicate_wrapper

export foobar="foobar"

tester="$testdir/aux/functions-print-env"
[[ -x "$tester" ]] || { echo "$scriptname: cannot find auxiliary script '$tester'" >&2; exit 1; }

export PATH="$testdir/aux:$PATH"
comma_env --import=foobar,frobnicate,frobnicate_wrapper $( basename "$tester" )
