#!/bin/bash

ubuntu_version=$1
comma_version_major=$2
comma_version_minor=$3
comma_version_patch=$4
comma_dir="$5"
[[ -n "$comma_version_patch" ]] || { echo "usage: $0 <ubuntu version> <comma version major> <comma version minor> <comma version patch> [<comma dir>]" >&2; exit 1; }
[[ -n "$comma_dir" ]] || comma_dir="$( realpath ~/src/comma )"

docker run \
       --mount "type=bind,source=$( pwd ),target=/root/output" \
       ubuntu.$ubuntu_version.build.basics \
       /mnt/comma/system/package/comma-package-make $ubuntu_version $comma_version_major $comma_version_minor $comma_version_patch /mnt/comma || { echo "$0: failed" >&2; exit 1; }
