#!/bin/bash

source $( which comma-process ) || exit 1

export output_dir="output"
rm -rf "$output_dir" || exit 1
mkdir -p "$output_dir" || exit 1

# check that can run a bash function to completion and pass arguments through
# the environment
function function_to_execute()
{
    local arg1=$1
    local arg2=$2
    echo "arg[1]=\"$arg1\""
    echo "arg[2]=\"$arg2\""
}
export -f function_to_execute

function test01()
{
    output_file="$output_dir/test01.log"
    nap_time=5
    comma_execute_and_wait "bash -c function_to_execute $nap_time $output_file" >"$output_file"
    [[ -f "$output_file" ]] && cat "$output_file" | sed 's@^@test[1]/@'
}
test01 ; echo "test[1]/exit/status=$?"
