#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function unknown_fields
{
    python3 -c "$( cat <<END
import comma

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )

fields = 'unknown_field1,event/coordinates/y,event/coordinates/z,observer,event/time,event/coordinates/x,unknown_field2'
format = 'float64,float64,S3,datetime64[us],float64'
record_stream = comma.csv.stream( record_t, fields=fields, binary=True )

END
)"
}

unknown_fields
echo "status=$?"
