#!/bin/bash

echo "======== example 1: hello world =========================="
( echo hello; echo world; echo star=sun,antares,betelgeuse ) | ../../applications/name-value-form --title menu

echo "======== example 2: json ================================="
cat menu.json | name-value-convert | ../../applications/name-value-form --title menu | name-value-convert --to json

