#!/bin/bash
version=$1
comma_dir="$2"
[[ -n "$version" ]] || { echo "usage: $0 <ubuntu version> [<comma dir>]; e.g. $0 20.04" >&2; exit 1; }
[[ -n "$comma_dir" ]] || comma_dir=$( realpath ~/src/comma )
[[ -d "$comma_dir" ]] || { echo "usage: $0 please specify <comma dir> explicitly (since you seem to either run with sudo or have comma not in '$comma_dir')" >&2; exit 1; }
echo "$0: running:" >&2
echo "docker build -t ubuntu.$version.build.basics --build-arg version=$version --no-cache -f '$comma_dir/system/package/debian/Dockerfile' ." >&2
docker build -t ubuntu.$version.build.basics --build-arg version=$version --no-cache -f "$comma_dir/system/package/debian/Dockerfile" .
