#!/bin/bash

function comma_format_roundabout
{
    python -c "$( cat <<END
import comma
import numpy

numpy_format = comma.csv.types.format_to_numpy( '$1' )
numpy.dtype( numpy_format )
print comma.csv.types.format_from_numpy( numpy_format )
END
)"
}

while read name comma_format; do
    output=$( comma_format_roundabout $comma_format )
    status=$?
    echo "$name/output=$output"
    echo "$name/status=$status"
done
