#!/bin/bash

scriptname=$( basename "$0" )

function fcn()
{
    echo "argument/count=$#"
}
export -f fcn

app="./bin/script"
[[ -x "$app" ]] || { echo "$scriptname: executable '$app' not found" >&2; exit 1; }

source $( which comma-env-util ) || { echo "$scriptname: cannot source 'comma-env-util'" >&2; exit 1; }

comma_env --default $app 1 2 3 | sed 's@^@script/@'
comma_env --import=fcn bash -c fcn 1 2 3 | sed 's@^@function/@'
comma_env --default bash -c $app 1 2 3 | sed 's@^@explicit/@'
