#!/bin/bash

scriptname=$( readlink -f $0 )
source $( which comma-name-value-util ) || { echo "$scriptname: failed to source comma-name-value-util" >&2; exit 1; }

input="var_a=21
var_b=22"

echo "$input" | comma_path_value_mangle | sed 's|^|basic/|'

echo -n "$input" | comma_path_value_mangle | sed 's|^|no_newline_at_end/|'

echo "a/b/c=1" | comma_path_value_mangle | sed 's|^|path/|'
echo "a-b-c=1" | comma_path_value_mangle | sed 's|^|dashes/|'
echo "a/b-c=1" | comma_path_value_mangle | sed 's|^|path_with_dashes/|'
echo "a/b[0]=1" | comma_path_value_mangle | sed 's|^|subscript/|'
echo "a/b[0]/c=1" | comma_path_value_mangle | sed 's|^|subscript_followed_by_path/|'
