#!/bin/bash

source $( which comma-application-util )

function output { local prefix=$1; gawk '{ print "'${prefix:+$prefix/}'output/line["NR-1"]="$0 }' ; }

function process_records
{
    local input_format=$1
    python -c "$( cat <<END
import comma

point_t = comma.csv.struct( 'x', 'float64' )
if "$input_format":
    format = ','.join(comma.csv.format.to_numpy("$input_format"))
else:
    format = ''
record_stream = comma.csv.stream( point_t, fields=',x', format=format )

for i,r in enumerate( record_stream.iter(), start=1 ):
  r['x'] += i
  record_stream.write( r )
END
)"
}

input_format='2d'
output_format='d'

input=$( cat )
echo "$input" | process_records | output ascii
comma_status_ok
echo "ascii/status=$?"

echo "$input" | csv-to-bin $input_format | process_records $input_format | csv-from-bin $output_format | output binary
comma_status_ok
echo "binary/status=$?"

