#!/bin/bash

source $( which comma-process-util ) || exit 1
source "../detail/common-functions" || exit 1

export output_dir="output"
mkdir -p "$output_dir" || exit 1

function test04()
{
    export script=$( dirname "$0" )/../detail/tester
    [[ -x "$script" ]] || exit 1

    local output_dir="$output_dir/test04"
    rm -rf "$output_dir" || exit 1
    mkdir -p "$output_dir" || exit 1

    comma_execute_and_wait "$script 20 $output_dir/log1" "$script 15 $output_dir/log2"

    [[ -s "$output_dir/log1" ]] || exit 1
    [[ -s "$output_dir/log2" ]] || exit 1

    is_parallel=$( verify_parallel "$output_dir" )
    echo "test[4]/parallel=$is_parallel"
}

test04
echo "test[4]/exit/status=$?"
