#!/bin/bash

function handle_usr1()
{
    trap '' SIGTERM SIGHUP SIGPIPE SIGINT SIGUSR1
    exit 12
}

trap 'handle_usr1' SIGUSR1

function test05_trap()
{
    trap '' SIGTERM SIGHUP SIGPIPE SIGINT SIGUSR1
    echo "killed by $1"
    exit 11
}
export -f test05_trap

function test05_to_execute()
{
    trap 'test05_trap TERM' SIGTERM
    trap 'test05_trap HUP'  SIGHUP
    trap 'test05_trap PIPE' SIGPIPE
    trap 'test05_trap INT'  SIGINT
    trap 'test05_trap USR1' SIGUSR1

    echo "shell:" >&2
    ps -o pid,ppid,pgid,sid,stat,wchan,cmd -p $$ >&2

    comma-nap 20 --verbose &

    child_pid=$!
    echo "test05_to_execute: child_pid=$child_pid" >&2
    echo "child:" >&2
    ps -o pid,ppid,pgid,sid,stat,wchan,cmd -p "$child_pid" >&2
    wait $child_pid
    echo "child status=$?" >&2
    echo "$FUNCNAME: woken up"
}
export -f test05_to_execute

exec > "$output_file"
comma_execute_and_wait --show-debug-messages "bash -c test05_to_execute" --signals=TERM,HUP,USR1
