#!/bin/bash

source $( which comma-application-util )
function output { csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'; }

function missing_field
{
    python -c "$( cat <<END
import comma

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
stream = comma.csv.stream( point_t, fields='z,x', format='f8,f8' )
stream.write( stream.read() )
END
)"
}

csv-to-bin 2d | missing_field | csv-from-bin 3d | output
comma_status_ok
echo "status=$?"

