#!/bin/bash

source $( which comma-process-util ) || exit 1

export output_dir="output"
mkdir -p "$output_dir" || exit 1

function test05()
{
    (
        scriptdir=$( dirname "$0" )/detail
        script="$scriptdir"/test05-script
        [[ -x "$script" ]] || exit 1
        # will kill the function by timer (which is shorter than expected run-time)
        timeout -k 10 -s USR1 5 "$script"
    )
}

echo "pretest" >&2
bash -c '
    sleep 10 &
    p=$!
    echo "pid=$p"
    ps -o pid,ppid,pgid,sid,stat,cmd -p "$p"
    grep -E "^Sig(Ign|Blk|Cgt):" /proc/$p/status
    kill -TERM "$p"
    wait "$p"
    echo "wait status=$?"
'
echo "pretest done" >&2

export output_file="$output_dir/test05.log"
test05
echo "test[5]/exit/status=$?"
echo "test[5]/output=\""$( cat "$output_file" )"\""
