#!/bin/bash

while IFS='=' read key value ; do
    [[ -n "$key" && "${key:0:1}" != "#" ]] || continue
    value="${value/#\"}"
    value="${value/%\"}"
    status=1
    output="$( eval "$value" 2>/dev/null || exit 1 )"
    [[ $? == 0 ]] || status=0
    echo "$( dirname "$key" )/output=\"$output\""
    echo "$( dirname "$key" )/status=$status"
done < <( grep '=' ; grep -v '^#' )
