#!/bin/bash

name=$( basename "$0" )

source $( which comma-application-util ) || { echo "$name: cannot source 'comma-application-util'" >&2; exit 1; }

comma_path_value_to_var --prefix=input --export

function main()
{
    local value_type
    value_type=${input_value_type:+"value_type=$input_value_type, "}
    python -c "
from __future__ import print_function
import comma.application
import argparse

parser = argparse.ArgumentParser( )
parser.add_argument( '--dict', metavar='DICT', help='populate a dictionary of given type', type=str, action=comma.application.set_dictionary_action, $value_type delimiter=';', default={} )
args = parser.parse_args()
for k, v in args.dict.iteritems():
    def quote_if_string( v ):
        if type( v ) == str:
            return '\"%s\"' % v
        else:
            return v
    print( '%s=%s' % ( k, quote_if_string( v ) ) )
" $input_args
}

main
echo "status=$?"
