#!/bin/bash

function process_records_fields_has_extra_names
{
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )
record_stream = comma.csv.stream( record_t, fields='f0,event/coordinates/y,event/coordinates/z,observer,f1,event/time,event/coordinates/x,f2/subfield,f3' )

for i,r in enumerate( record_stream.iter(), start=1 ):
  r['observer'] = numpy.char.upper( r['observer'] )
  r['event']['time'] += numpy.timedelta64( i, 's' )
  r['event']['coordinates']['x'] += i
  record_stream.write( r )
END
)"
}

output="$( process_records_fields_has_extra_names )"
status=$?
echo "$output" | csv-paste value="line[" line-number value="]\=" --delimiter '@' - | sed 's/@//g'
echo "status=$status"
