#!/bin/bash

source $( which comma-application-util )

function output { local prefix=$1; gawk '{ print "'${prefix:+$prefix/}'output/line["NR-1"]="$0 }' ; }

function process_records
{
    local binary
    if [[ "$1" == "binary" ]]; then binary=True; else binary=False; fi
    python -c "$( cat <<END
import comma
import numpy

point_t = comma.csv.struct( 'x,y,z', 'float64', 'float64', 'float64' )
timestamped_point_t = comma.csv.struct( 'time,coordinates', 'datetime64[us]', point_t )
record_t = comma.csv.struct( 'observer,event', 'S3', timestamped_point_t )
record_stream = comma.csv.stream( record_t, binary=$binary )

for i,r in enumerate( record_stream.iter(), start=1 ):
  r['observer'] = numpy.char.upper( r['observer'] )
  r['event']['time'] += numpy.timedelta64( i, 's' )
  r['event']['coordinates']['x'] += i
  record_stream.write( r )
END
)"
}

input=$( cat )
echo "$input" | process_records | output ascii
comma_status_ok
echo "ascii/status=$?"

echo "$input" | csv-to-bin s[3],t,3d | process_records binary | csv-from-bin s[3],t,3d | output binary
comma_status_ok
echo "binary/status=$?"
