#!/bin/bash

read args
read format

output_cmd="cat"
[[ -z "$format" ]] || output_cmd="csv-from-bin $format"

csv-thin $args | $output_cmd >"output/out"

cat "output/out" | cat -n | sed 's#^ *#output[#;s#\t#]="#;s#$#"#'


