#!/bin/bash


source $( type -p comma-application-util )

function mangle_options() { comma-options-to-name-value "$@" | { grep '='; :; } | comma_path_value_mangle | sed 's/^/local options_/g'; comma_status_ok; }

function description()
{
    cat <<EOF
--help,-h; output instructions for using this program and exit
--from=[<what>]; choices: ini, json, path-value, yaml, xml, all sources are of that type, if --from=path-value, pass inputs through verbatim
--indented; if --to xml, output indented
--minify; if --to json, output minified
--output-source,--source; for each name, output the name of the source config from which value comes instead of the value itself
--to=<what>; default=path-value; choices: ini, json, path-value, xml
--unquote-numbers,-u; unquote numbers
EOF
}

function bash_completion() { description | sed 's/=.*//g' | sed 's/;.*//g' | sed 's/,/\n/g' ; }

function prologue()
{
    cat >&2 <<eof

take multiple path-value inputs, apply on top of each other
    
e.g: assume we have a default config file and then the user would like to set just some values and leave
     the rest as default; then we simply apply the user's config on top of default as in examples below

usage
    name-value-apply [<options>] <file> [<file>...]
    <file>: <path>|'-'
            '-': stdin

eof
}

function epilogue()
{
    cat<<eof
examples
    basics
        echo '{ "a": "hello", "b": "world" }' | name-value-apply - <( echo "a=bye" ) --to json
        {
            "a": "bye",
            "b": "world"
        }

    a bit more
        > ( echo a=5; echo b=hello ) > config1.pv; ( echo '{ "a": 6, "c": 8 }' ) > config2.json

        > name-value-apply config1.pv config2.json --unquote-numbers
        a=6
        b="hello"
        c=8

        > name-value-apply --source config*
        a="config2.pv"
        b="config1.pv"
        c="config2.pv"

eof
}

(( $( comma_options_has --bash-completion $@ ) )) && { bash_completion; exit 0; }
comma-application-init "$@" < <( description )
(( !options_unquote_numbers )) || unquote_numbers_option="--unquote-numbers"
(( !options_minify )) || minify_option="--minify"
(( !options_indented )) || indented_option="--indented"
[[ -z "$options_from" ]] || from_option="--from=$options_from"
for f in "${options_unnamed[@]}"; do
    cat "$f" \
        | if [[ "$options_from" == 'path-value' ]]; then cat; else name-value-convert $from_option; fi \
        | if (( options_output_source )); then cut -d= -f1 |  sed "s~$~=\"$f\"~g"; else cat; fi
done | name-value-convert --take-last --to $options_to $unquote_numbers_option $indented_option $minify_option

