#!/bin/bash

name=$( basename $0 )

function handle()
{
    [[ -n "$workdir" ]] && rm -rf "$workdir"
}

trap 'handle' EXIT

output_dir="output"
rm -rf "$output_dir" || exit 1
mkdir -p "$output_dir" || exit 1
output_dir=$( realpath "$output_dir" )

tarball="../data/sample.tar"
[[ -f "$tarball" ]] || {
    echo "$name: file '$tarball' not found" >&2
    exit 1
}
tarball=$( realpath "$tarball" )

workdir=$( mktemp --directory )
cd "$workdir"
tar xf "$tarball" || exit 1
cd sample || exit 1
comma-test-run --raw $@ > "$output_dir/log" 2>&1
(( $? == 0 )) || exit 1

# mangle the log to print a list of which test script was invoked in a given directory
# directory name becomes the path and the script name the value in path=value format
# brief explanation of all the sed actions:
# - delete the first and last lines
# - delete the comma-test-run prefix
# - for lines ending with 'running...' join the next line
# - delete all up to the first ':' and a bit more (leading './')
# - delete from the (next) ':' and up to 'called', insert '="' instead
# - remove the closing '}', insert '"' instead
# - remove lines that contain success statement (do not bother with failure, if any test fails
#   we bomb out earlier)
# - one of the test needs a suffix, just to please comma-test-match
cat "$output_dir/log" | sed '1d;$d;s/^comma-test-run: //' | sed '/running...$/N;s@^[^:]*: ./@@;s@:.*{called @="@;s@}$@"@' | sed '/succeeded/d' | sed 's@dir5/subdir3=@dir5/subdir3/here=@'
exit 0
