#!/bin/bash

name=$( basename $0 )

function handle()
{
    [[ -n "$workdir" ]] && rm -rf "$workdir"
}

trap 'handle' EXIT

output_dir="output"
output_dir=$( readlink -f "$output_dir" )

tarball="../data/sample.tar"
[[ -f "$tarball" ]] || {
    echo "$name: file '$tarball' not found" >&2
    exit 1
}
tarball=$( readlink -f "$tarball" )

workdir=$( mktemp --directory --tmpdir="$output_dir" )
cd "$workdir"
tar xf "$tarball" || exit 1
cd sample || exit 1
comma-test-run --raw --white-list=white.list --black-list=black.list $@ > "$output_dir/log" 2>"$output_dir/log2"
(( $? == 0 )) || exit 1

elapsed="stats/elapsed.csv"
[[ -r "$elapsed" ]] || exit 1
cat "$elapsed" | sed 's@^\./@@'
