#!/bin/bash

name=$( basename $0 )

source $( type -p comma-test-util ) || exit 1

mkdir -p 'output' || exit 1
export output_dir="$( readlink -f 'output' )"

comma_test_run_tarball '../data/sample.tar'  --white-list=white.list --black-list=black.list

elapsed="stats/elapsed.csv"
[[ -r "$elapsed" ]] || { echo "Could not access '$elapsed'" >&2 ; exit 1 ; }
cat "$elapsed" | sed 's@^\./@@'

exit 0
