#!/bin/bash

testdir=$( dirname "$0" )
scriptname=$( basename "$testdir" )/$( basename "$0" )

source $( which comma-env-util ) || exit 1

tester="$testdir/aux/default-print-env"
[[ -x "$tester" ]] || { echo "$scriptname: cannot find auxiliary script '$tester'" >&2; exit 1; }

export PATH="$testdir/aux:$PATH"
comma_env --default $( basename "$tester" )
