#!/bin/bash

source $( which comma-process-util ) || exit 1

export output_dir="output"
mkdir -p "$output_dir" || exit 1

function test04_outer_handler()
{
    echo "handle $1"
    exit 0
}
export -f test04_outer_handler

function test04_to_execute()
{
    # comma-nap 10 &
    # wait $!

    strace -ff -tt -o output/sleep.strace sleep 10 &
    sleep_pid=$!

    echo "started sleep pid=$sleep_pid" >&2
    ps -o pid,ppid,pgid,sid,stat,cmd -p "$sleep_pid" >&2

    wait "$sleep_pid"
    status=$?

    echo "wait returned status=$status" >&2
    ps -o pid,ppid,pgid,sid,stat,cmd -p "$sleep_pid" >&2

    return "$status"
}
export -f test04_to_execute

function test04_to_be_killed()
{
    trap 'test04_outer_handler TERM' SIGTERM
    trap 'test04_outer_handler HUP'  SIGHUP
    trap 'test04_outer_handler PIPE' SIGPIPE
    trap 'test04_outer_handler INT'  SIGINT
    #
    comma_execute_and_wait --show-debug-messages "bash -c test04_to_execute" > $output_file
}
export -f test04_to_be_killed

function test04()
{
    (
        # will kill the function by timer (which is shorter than expected run-time)
        timeout -k 10 -s TERM 5 bash -c test04_to_be_killed
    )
}

export output_file="$output_dir/test04.log"
test04
echo "test[4]/exit/status=$?"
echo "test[4]/output=\""$( cat "$output_file" )"\""
