#!/bin/bash

function ambiguous_fields
{
    python3 -c "$( cat <<END
import comma
import numpy

a1 = comma.csv.struct( 'a,b,c', 'float64', 'float64', 'float64' )
a2 = comma.csv.struct( 'a,b', 'float64', 'float64' )
record_t = comma.csv.struct( 'a1,a2', a1, a2 )
record_stream = comma.csv.stream( record_t, fields='a,b,c', full_xpath=False )

END
)"
}

ambiguous_fields
echo "status=$?"

