#!/bin/bash

dir=output

[[ -d "$dir"  ]] || mkdir $dir

cat >$dir/test.csv
csv-to-bin 's[1],4ui' <$dir/test.csv >$dir/test.bin

exec 3<> $dir/test.csv

for i in {1..5} ; do
    csv-blocks head --fields=,,,,index <&3 \
        | sed 's#\(.*\)#"\1"#'";s#^#ascii/run[$i]=#;"
done | gawk '{ print "line["NR"]/"$0; }'
exec 3>&-

exec 3<> $dir/test.bin
for i in {1..5} ; do
    csv-blocks head --fields=,,,,index  --binary 's[1],4ui' <&3 \
        | csv-from-bin 's[1],4ui' \
        | sed 's#\(.*\)#"\1"#'";s#^#binary/run[$i]=#"
done | gawk '{ print "line["NR"]/"$0; }'
exec 3>&-
