#!/bin/bash

# this script provides functions for interprocess syncronisation in bash

# this script is designed to be included in another script directly, for example:
# source $( which comma-sync )

[[ -n "$comma_sync_include_guard_" ]] && return
readonly comma_sync_include_guard_=1

# General synchronization function. Takes on input a lock file name to be used
# in a flock call (this file will be truncated to zero size) and the command to be
# executed with all the arguments. Example:
#
#     comma_locked /tmp/mylock myfcn --option1 "$value1" "$arg1" ...
#
# Note: do not re-direct output of the function being protected. Do all writes
# within a function while it is protected by the serialization lock.
#
# Note: internally, this function uses file descriptor 8. Avoid re-using it
# in your code that invokes (or invoked under) comma_locked.

function comma_locked()
{
    local lock=$1
    shift
    (
        flock -x 8
        $@
    ) 8>"$lock"
}
export -f comma_locked
