#!/bin/bash

function get_buffer_size_in_bytes { python3 -c "from __future__ import print_function; import comma; print( comma.csv.stream.buffer_size_in_bytes )"; }

function get_default_size
{
    local fields=$1
    local type=$2
    python3 -c "$( cat <<END
from __future__ import print_function
import sys
import comma
fields='$fields'
types = ('$type',) * len( fields.split(',') )
print( comma.csv.stream( comma.csv.struct( fields, *types ) ).size )
sys.stdout.flush() # have to flush, since stdout gets highjacked by comma.csv.stream (which kind of make sense)
END
)"
}

echo "buffer_size_in_bytes=$( get_buffer_size_in_bytes )"

fields="x,y"
echo "number_of_fields=$( python3 -c "from __future__ import print_function; s = '$fields'; print( len( s.split(',') ) )" )"
echo "size/uint8=$( get_default_size $fields uint8 )"
echo "size/float64=$( get_default_size $fields float64 )"
