#!/bin/bash

scriptname=$( basename $0 )

source $( which comma-process-util ) || exit 1
source $( which comma-application-util ) || exit 1

source $( type -p comma-test-util ) || exit 1

mkdir -p 'output' || exit 1
outdir="$( readlink -f 'output' )"

comma_test_util_run_tarball '../data/timeout.tar' "--junit=$outdir/junit.xml"

# output_directory="$( name-value-get --from path-value 'output_directory' <<< "$result" )"

cat "$outdir/junit.xml" | name-value-convert --from xml --to path-value | sed 's@[<>]@@g'
comma_status_ok || exit 1

