#!/bin/bash

scriptname=$( basename $0 )

source $( which comma-process-util ) || exit 1
source $( which comma-application-util ) || exit 1

success_test_dir="output/returns_success"
failure_test_dir="output/returns_failure"

function cleanup()
{
    # need to remove "test" files, otherwise comma-test-run will think they are a real test next time
    rm -f $success_test_dir/test $failure_test_dir/test
}

trap "cleanup" EXIT
output_dir=$( readlink -f "output" )

mkdir -p $success_test_dir || exit 1
cat > "$success_test_dir/test" <<EOF 
#!/bin/bash
exit 0
EOF
chmod u+x "$success_test_dir/test"
mkdir -p "$failure_test_dir" || exit 1
(
    cd $success_test_dir
    comma-test-run --raw > "comma-test-run.log" 2>&1
    echo "returns_success/status=$?"
)

cat > "$failure_test_dir/test" <<EOF 
#!/bin/bash
exit 9
EOF
chmod u+x "$failure_test_dir/test"
(
    cd "$failure_test_dir"
    comma-test-run --raw > "comma-test-run.log" 2>&1
    echo "returns_failure/status=$?"
)
