#!/bin/bash

output_dir="output"
mkdir -p "$output_dir" || exit 1

dummy="$output_dir/dummy"
touch "$dummy" || exit 1

utc_time=$( date -u +%Y%m%dT%H%M%S --reference="$dummy" )
local_time=$( date +%Y%m%dT%H%M%S --reference="$dummy" )

echo "utc=\"$utc_time\""
echo "utc_to_local=\"$( echo "$utc_time" | csv-time --to local )\""
echo "local=\"$local_time\""
echo "local_to_utc=\"$( echo "$local_time" | csv-time --from local )\""
