#!/usr/bin/python
import numpy as np
import comma
t = comma.csv.struct( 'id,value', 'u4', 'f8' )
s = comma.csv.stream( t, binary=True )
max = {}
for data in s:
    for id in np.unique(data['id']).tolist():
        current_max = data['value'][data['id']==id].max()
        if id in max and current_max <= max[id]:
            continue
        max[id] = current_max
s.write(np.array(max.items(), dtype=t))

