#!/bin/bash

name=$( basename $0 )

tmp_dir="/tmp"
results="$tmp_dir/comma-test-run_result.$$"
expected="expected_results"
quiet=0

function usage()
{
    cat <<EOF

todo
    
usage: $name

EOF
    exit
}

[[ "$1" != "--help" && "$1" != "-h" ]] || usage

function bye() { rm -f "$results" ; exit $1 ; }

trap 'bye 1' SIGHUP SIGINT SIGTERM SIGPIPE

current_dir=$( pwd )
cd $( dirname $0 )/data
comma-test-run 2>&1 | sed 's/in subdirectories of [^:]*/in subdirectories of DIR/g' > "$results"
diff -b "$results" "$expected" > /dev/null

if [[ $? != 0 ]]; then
    echo "$name: failed with the following differences:" >&2
    diff -b "$results" "$expected" >&2
    bye 1
fi
cd $current_dir

( cd $( dirname $0 )/comma_test_run ; comma-test-run )

bye $?
