#!/bin/bash

source $( which comma-process-util )
scriptname=$( readlink -e $0 )
scriptpid=$$

dir=output
mkdir -p $dir
normal_log=$dir/normal.log
killed_log=$dir/killed.log
rm -f $normal_log $killed_log

comma_nap=$( which comma-nap )

comma-execute-and-wait $comma_nap 1 > $normal_log
status=$?
output=$( cat $normal_log )
echo "normal/output=\"$output\""
echo "normal/status=$status"

function allow_comma_execute_and_wait_to_launch
{
    local output_file=$1
    local -i timeout=60
    SECONDS=0
    while true; do
        (( SECONDS < timeout )) || { echo "$scriptname: timed out after $timeout seconds while waiting for $comma_nap to start" >&2; exit 1; }
        sleep 0.01
        pstree $scriptpid | grep comma-nap &>/dev/null || continue
        test -f $output_file || continue
        break
    done
}

nap_time=30 
comma-execute-and-wait $comma_nap $nap_time > $killed_log & pid=$!
allow_comma_execute_and_wait_to_launch $killed_log
kill $pid &>/dev/null
wait $pid &>/dev/null
sleep $( bc -l <<< "$nap_time + 5" )
echo "killed/output=\"$( cat $killed_log )\""

